### ISSUE TITLE
Request for PM2.5 sensors

### ISSUE THREAD

**Issue by CODeRUS** [ptvoinfo/zigbee-configurable-firmware#1]
It uses i2c bus, usually

Specially SPS30 one i am owning :)

**Comment by ptvoinfo** [comment]
The firmware support Sensair and MHZ19. Is it the same?

**Comment by CODeRUS** [comment]
Senseair is co2, sps. Is pm2.5
Check https://esphome.io/components/sensor/sps30.html

**Comment by ptvoinfo** [comment]
Ok. I see. Unfortunately, this sensor is rather expensive and I cannot purchase it for development.

**Comment by CODeRUS** [comment]
Pm me in telegram or something, i can donate

**Comment by ptvoinfo** [comment]
If you can donate for the sensor, I can try to add it in the UART mode (requires fewer resources). Could you say your nickname in Tg?

**Comment by CODeRUS** [comment]
sure, i am @icoderus in tg

**Comment by Omirax** [comment]
Yes.Yes.Yes! Integration of SDS011 is badly needed!

**Comment by ptvoinfo** [comment]
Added SDS30
