### ISSUE TITLE
Feature request: support multiple i2c 

### ISSUE THREAD

**Issue by juliend20** [ptvoinfo/zigbee-configurable-firmware#102]
First, thank you so much for your great work. It's very interesting to create your own sensors/actuators.

I bought two waterproof sensors SHT30. But I cannot change the i2c address and I cannot access the address pin on the chip.
Can I configure two separate i2c like that?

P01      SHT30 (I2C SDA)
P02      I2C SCL

P03      SHT30 (I2C SDA)
P04      I2C SCL

But how the firmware knows the right SCL pin?

**Comment by ptvoinfo** [comment]
Hi,

Your configuration is correct. I2C busses are: P01 & P02, P03 & P04.

**Comment by juliend20** [comment]
Hi, This is very great 👍. Thank you so much.
