### ISSUE TITLE
Pulse switch output changes input.

### ISSUE THREAD

**Issue by tagy** [ptvoinfo/zigbee-configurable-firmware#103]
Hi, I am trying to make a device with 3 buttons and 3 LEDs.

When you click a button the LED next to that button will blink and it will send a report of the button pressed.

![Capture](https://user-images.githubusercontent.com/3080666/160283564-24edddbb-4a3d-4ca1-84d3-189ea69b8e33.JPG)

This gives me something close to what I want, but when I click a button I get:

`Zigbee2MQTT:info  2022-03-27 14:16:07: MQTT publish: topic 'zigbee2mqtt/0x00124b00061df10f', payload '{"linkquality":87,"state_l1":"OFF","state_l2":"OFF","state_l3":"OFF"}'
`

Then clicking button1 again:

`Zigbee2MQTT:info  2022-03-27 14:16:09: MQTT publish: topic 'zigbee2mqtt/0x00124b00061df10f', payload '{"linkquality":94,"state_l1":"ON","state_l2":"OFF","state_l3":"OFF"}'
`

So it only sends the state not the button that was pressed, so I would need to compare messages to the previous message to see what was clicked.

If I untick the 'link to output' I get the following:

`Zigbee2MQTT:info  2022-03-27 14:13:10: MQTT publish: topic 'zigbee2mqtt/0x00124b00061df10f', payload '{"action":"single_l1","linkquality":83,"state_l1":"OFF","state_l2":"OFF","state_l3":"OFF"}'
`

It now has an action I can use to see what button was clicked. Can I have the pulse switch (blinking LED) and the action? Thanks.

**Comment by ptvoinfo** [comment]
No, you cannot have the "action" value for a linked button. 

In your case, state_l1 means Button #1, and state_l2 - Button #2.
