### ISSUE TITLE
commandToggle for bound devices

### ISSUE THREAD

**Issue by ptvoinfo** [ptvoinfo/zigbee-configurable-firmware#104]
Add an option to select and send `commandToggle` for bound devices instead of `commandOn/commandOff` (requested in #96) because `commandToggle` allows avoiding asynchronous behavior of a button and a bound device.

e.g.
1. Bulb is on, sonoff mini is on
1. Switch physical switch,  sonoff mini turns off -> sends `commandOff` -> bulb turns off
1. Turn bulb on via zigbee2mqtt -> bulb turns on
1. Switch physical switch -> sonoff mini turns on -> sends `commandOn` -> nothing happens at the bulb since it was already on. You would expect it to turn off here.

**Comment by ptvoinfo** [comment]
@Koenkk Could you please try the update? I've added this feature.

![изображение](https://user-images.githubusercontent.com/33662022/161532882-ea2c5f37-857a-47ec-9908-b4af276dca02.png)

**Comment by Koenkk** [comment]
Flashed the following on my sonoff zb mini:
![image](https://user-images.githubusercontent.com/2892853/161830179-dece0e06-6601-4121-bcaf-3d2907182545.png)

Paired it to zigbee2mqtt, and connected a switch to S1/S2. Toggling the switch correctly toggles the relay (device keeps working)

Next I bound endpoint 2 genOnOff to coordinator ep 1:

<img width="1347" alt="Screenshot 2022-04-05 at 21 02 58" src="https://user-images.githubusercontent.com/2892853/161830336-9eeb269b-3c2e-4c87-9431-0ae46bf6cab2.png">

Toggled the switch again, which sends an ON command (I expected a toggle here) AND the zb mini stops responding, no more actions after toggling the switch (relay doesn't click anymore + no zigbee traffic)

<img width="998" alt="Screenshot 2022-04-05 at 21 04 03" src="https://user-images.githubusercontent.com/2892853/161830482-b626a4d1-e0f1-4156-a0c0-1e92a154d91d.png">

**Comment by ptvoinfo** [comment]
Could you please bate my curiosity, why do you bind an endpoint with a coordinator?

**Comment by Koenkk** [comment]
I'm testing the firmware in a simple setup first with just the coordinator and the sonoff mini in the network. But it shouldn't be different than binding it to a group or device.

**Comment by ptvoinfo** [comment]
@Koenkk You can press and hold Input 1 (P23) for 10 seconds.

**Comment by Koenkk** [comment]
@ptvoinfo works perfectly, thanks, I'm really happy with this 😄
