### ISSUE TITLE
Group switch limited to "2,3,4"? Renders as dropdown instead of edit box.

### ISSUE THREAD

**Issue by RaNo99** [ptvoinfo/zigbee-configurable-firmware#105]
When selecting "Group switch" for an output, the "Outputs" property is a dropdown with only one option: "2,3,4". I guess this is a bug in version 1.6.1.2. It should be a text field instead.

![ptvo](https://user-images.githubusercontent.com/3323632/161401784-8f4efd7f-4c7e-4976-96cd-cfabb46b7e33.png)

Version 1.5.2.5 worked fine - the property is an edit box where you can put any output values.
Please fix or share the code so that I could fix myself :)

**Comment by ptvoinfo** [comment]
@RaNo99 Resolved in the latest version,

**Comment by RaNo99** [comment]
Wow, thanks for quick turnaround!
