### ISSUE TITLE
Group switch supports 8 outputs only, even in Premium version.

### ISSUE THREAD

**Issue by RaNo99** [ptvoinfo/zigbee-configurable-firmware#107]
Hi, I have a configuration as follows in the Premium version:
![ptvo2](https://user-images.githubusercontent.com/3323632/161621591-9c038727-40a8-4c79-ad3b-d6d2007e9a14.png)

Unfortunately these group switches switch outputs 1, 6, and 7 only. Outputs 9, 10, 11, and 12 do not react. It seems even the Premium version is limited to the first 8 outputs in this case?

As always, please fix, or share sources so that I can fix myself :) Thanks!

**Comment by ptvoinfo** [comment]
Hi @RaNo99,

Please try the update
https://ptvo.info/download/ptvo-firmware-2022-04-04.zip?t=1333556

**Comment by RaNo99** [comment]
Thanks! It worked, but not with the version you linked above, but with the one from the official downloads page (2022-04-05).
