### ISSUE TITLE
Add support for HX711 Load Cell Amplifier

### ISSUE THREAD

**Issue by Hollla12** [ptvoinfo/zigbee-configurable-firmware#108]
Hi, thanks for the firmware configurator! 

I was wondering if it's possible to add another input, the HX711, so that I can attach a balance and send the weight via Zigbee.

Thank you very much.

**Comment by ptvoinfo** [comment]
Hi @Hollla12. Sorry, but I didn't plan to add support for this sensor.

**Comment by bojanpotocnik** [comment]
@ptvoinfo have you ever considered open-sourcing just a part of the FW, kind of creating an interface (e.g. ESPHome style) so we could implement our own sensors, or create PRs with e.g. 80% of the work done, you would just need to integrate?
