### ISSUE TITLE
CC2530 + CC2591 will not route after powerloss.

### ISSUE THREAD

**Issue by frankhommers** [ptvoinfo/zigbee-configurable-firmware#11]
I have flashed my CC2530 + CC2591 with the firmware.

I also have entered my network key inside in the "Firmware Configuration" tool.

When I plug it in and pair my devices everything works, until I remove power from it.
Afterwards I need to repair everything to make it work again....

Is this a bug or as designed?

**Comment by ptvoinfo** [comment]
@frankhommers I didn't see this issue with my routers. The device may lose a route when the router is offline. But they should return after some time.

**Comment by frankhommers** [comment]
I have now added two Osram Plugs and now it keeps working stable.
