### ISSUE TITLE
Dc motor + ina219

### ISSUE THREAD

**Issue by celium** [ptvoinfo/zigbee-configurable-firmware#111]
Hello :) 

It is possible when ina219 measure mAh automatically turn off dc motor? I Want create blinds with your firmware but when blinds is  close motor automatically turn off. Such as when motors closing blinds mAh is 120mah and when blinds is close motors mah is 160mah and when all mah upper 140mah automatically turn off motor. Imagination i want create virtual switch via meassure mah with ina219

Thanks ;)

**Comment by ptvoinfo** [comment]
Sorry, but this application is not possible with the standard firmware because the firmware measures current only when it sends a report to a coordinator.
