### ISSUE TITLE
Modbus 32bits non-standard 

### ISSUE THREAD

**Issue by nikito7** [ptvoinfo/zigbee-configurable-firmware#116]
Standard 32bits are  two registers 
16bits+16bits = count 2

My meter use a single register for 32bits
32bits = count 1

Can you add support?

Thank you

**Comment by ptvoinfo** [comment]
Sorry, it is the very rare case. It is too hard to implement this feature

**Comment by nikito7** [comment]
Depending on how your code works.

It's only need to change request code.

Decoder code will be the same.

Normal modbus request
01 03 00 AA 00 02 crc

"32bits single register" modbus request
01 03 00 AA 00 01 crc

The response will be the same 

01 04 DD DD DD DD crc

**Comment by nikito7** [comment]
![20220507_024102](https://user-images.githubusercontent.com/45373783/167232995-c085f40e-e495-4aae-9e12-9edb08e10e45.jpg)

The easy way is a new uint32 type
