### ISSUE TITLE
CC2530 and AJ-SR04

### ISSUE THREAD

**Issue by valentintintin** [ptvoinfo/zigbee-configurable-firmware#120]
Hello,

I've got a small issue if you can provide some help it could be very good!

I ordered these boards:
- https://fr.aliexpress.com/item/1005001376470705.htm (CC2530)
- https://fr.aliexpress.com/item/1005003683104654.html (AJ-SR04M)

I plugged my sensor as your tutorial here : https://ptvo.info/zigbee-configurable-firmware-features/external-sensors/ultrasonic-sensors-us100-or-hc-sr04/

**The blue LED of the sensor turns off when the I plug the trigger wire (P06 <> I2C SCL) and never turns on (or blinks).**
I also tried to use P20 as I2C SCL because I saw that the LED stay on when I plugged the wire on it but as soon as I flash the new firmware with the P20 selected, the LED turns off.

On an Arduino Uno, I don't have any issue and the sensor gives me the correct value and the blue LED blinks as the same time as the Arduino sends a trigger, even at 3.3V.

On Zigbee2Mqtt, _i1_ and _i2_ are null, whereas _i3_ and _i4_ are good (source voltage and uptime).

Here is the config I use for your firmware: 
![image](https://user-images.githubusercontent.com/12508070/169275820-2cd4e978-f816-4dbc-8155-a21ff2b4872f.png)

Thanks for your time,
Valentin

**Comment by ptvoinfo** [comment]
Hello,

Did you select "Mode2" on the sensor? You can also try serial port mode and the US-100 sensor in the firmware.

**Comment by ptvoinfo** [comment]
Confirmed, works in the UART mode.

**Comment by McRMX** [comment]
> Hello,
> 
> Did you select "Mode2" on the sensor? You can also try serial port mode and the US-100 sensor in the firmware.

How we can select Mode 2 ?

**Comment by ptvoinfo** [comment]
@McRMX There are free pads for a resistor. If you place a jumper there, the device start working in the UART mode.

**Comment by McRMX** [comment]
Ok thanks

But there is different kind of device.

I don't find the good documentation, do you now on this one.

![IMG_4773](https://user-images.githubusercontent.com/54727223/197611812-3477e57d-2214-4dd6-bc8a-06e7feea04bd.png)

After this on the application, configuration is differente. I need to choose this one ?
![Capture d’écran 2022-10-24 à 21 45 24](https://user-images.githubusercontent.com/54727223/197612445-83eaa5d0-8b90-491a-a46a-dd7e9531dd9c.png)

**Comment by ptvoinfo** [comment]
I suppose you should place a jumper on R19.
