### ISSUE TITLE
CC2530 E18-MSB1-PCB and HC-SR04

### ISSUE THREAD

**Issue by Tb7386** [ptvoinfo/zigbee-configurable-firmware#125]
Hello,
I flash E18-MS1-PCB with PTVO firmware with same configuration for connect HC-SR04.
![Capture d’écran du 2022-06-15 23-43-09](https://user-images.githubusercontent.com/59627714/173939956-edc94a9c-88f3-4eb1-947f-76d4da85653b.png)
Status led slow flash when it’s associate with zigbee2mqtt but I don’t receive any distance value.
I check signal with SALEAE on pin P05(18) and pin P06(17) :
– P05 stay at low level.
– P06 stay at high level.
Firmware never send trigger signal.
![Capture d’écran du 2022-06-16 00-52-20](https://user-images.githubusercontent.com/59627714/173955283-6f843894-db01-448d-8c6e-e0c6de5eb0e8.png)

What I do false ?

**Comment by ptvoinfo** [comment]
Hello,

Did you enable periodic reports on the "Expert" tab?

**Comment by Tb7386** [comment]
Hello, thank you for your help.
My sensor works with Arduino and an example sketch like: https://www.carnetdumaker.net/articles/mesurer-une-distance-avec-un-capteur-ultrason-hc-sr04-et-une-carte-arduino- genuine/
I'm testing this configuration:
![Capture d’écran du 2022-06-16 23-58-09](https://user-images.githubusercontent.com/59627714/174177226-23c88883-fbf2-4b60-a230-ec8133269068.png)

Analyzing it with Saleae shows the trigger signal and the echo return signal with correct measure (~ 1.5m)
![Capture d’écran de 2022-06-17 00-02-13](https://user-images.githubusercontent.com/59627714/174182516-3616b583-ce6c-43d1-99e6-710202405208.png)

But no data sent to Zigbee2MQTT.
I tried to modify Manufacture and model ID. I import converter for Z2M.
![Capture d’écran du 2022-06-17 00-04-44](https://user-images.githubusercontent.com/59627714/174184319-e61f45e1-6d26-4ef1-bc03-df9c6ed73303.png)

 In Z2M, device seen like ptvo.switch. No distance measurement in log.

**Comment by Tb7386** [comment]
I tried to change PIN too. But issue is the same

**Comment by 1GOR19** [comment]
> Здравствуйте, спасибо за помощь. Мой датчик работает с Arduino, и пример эскиза такой: [https://www.carnetdumaker.net/articles/mesurer-une-distance-avec-un-capteur-ultrason-hc-sr04-et-une-carte-arduino-подлинное](https://www.carnetdumaker.net/articles/mesurer-une-distance-avec-un-capteur-ultrason-hc-sr04-et-une-carte-arduino-) / Я тестирую эту конфигурацию: ![Захват экрана от 16 июня 2022 г., 23 мая 2022 г.](https://user-images.githubusercontent.com/59627714/174177226-23c88883-fbf2-4b60-a230-ec8133269068.png)
> 
> Анализ с помощью Saleae показывает сигнал запуска и обратный эхо-сигнал с правильным размером (~ 1,5 м). ![Захват экрана от 17 июня 2022 г., 13 февраля 2022 г.](https://user-images.githubusercontent.com/59627714/174182516-3616b583-ce6c-43d1-99e6-710202405208.png)
> 
> Но данные в Zigbee2MQTT не отправляются. Я попытался изменить идентификатор производителя и модели. Импортирую конвертер для Z2M. ![Захват экрана от 17 июня 2022 г., 44 апреля 2022 г.](https://user-images.githubusercontent.com/59627714/174184319-e61f45e1-6d26-4ef1-bc03-df9c6ed73303.png)
> 
> В Z2M устройство отображается как ptvo.switch. В журнале нет измерения расстояния.

Were you able to transfer distance data to Z2M?
