### ISSUE TITLE
shtc3 не работает

### ISSUE THREAD

**Issue by Garkus98** [ptvoinfo/zigbee-configurable-firmware#126]
shtc3 на последней прошивке от 30 мая не работает на 2652p и 2530.

**Comment by ptvoinfo** [comment]
I cannot confirm this problem. Tested on CC2652P. The I2C address is 0x70 (hex) or 112 (dec)

**Comment by Garkus98** [comment]
Я прошел логическим анализатором и там тишина. на 2652p

**Comment by ptvoinfo** [comment]
Please attach a screenshot with your firmware settings.

**Comment by Garkus98** [comment]
![2](https://user-images.githubusercontent.com/76440047/176371443-da5d3333-a1e5-490f-9c5e-bb1e57f775cf.png)
![1](https://user-images.githubusercontent.com/76440047/176371446-fdf94c75-1e29-4f00-9f02-62b75d3dc14e.png)

**Comment by ptvoinfo** [comment]
Do you really have the external pull-up resistor on I2C wires? The standard SHTC3 sensor does not have them inside.

**Comment by Garkus98** [comment]
да там есть

**Comment by ptvoinfo** [comment]
The firmware checks the ID of the SHTC3 sensor. Some Chinese clones use another sensor ID. Therefore, the firmware cannot detect these sensors properly.

**Comment by Garkus98** [comment]
Да Мы с вами уже это увидели когда я вам отправил с логического анализатора данные и вы отправили спец версию прошивки.
