### ISSUE TITLE
Vitual binary switches/sensors?

### ISSUE THREAD

**Issue by Ruxton** [ptvoinfo/zigbee-configurable-firmware#13]
Could it be a possible feature in the future, that UART commands could define Zigbee switches/buttons?

This way outside of Z2M, the device is presenting zigbee switches for commands defined in the firmware. 

I'm trying to [recreate this](https://github.com/fenderle/esphome-vorke-hd41/blob/master/vorke_hd41.h) but in zigbee with cc2530.
The [device has an Rs232](http://www.vorke.com/project/vorke-hd41-pro/ ) port and I communicate fine with it, but it'd be nice if the device could present each command as a switch.

**Comment by ptvoinfo** [comment]
Hello,

This feature requires a dedicated firmware. You may add an Arduino in the middle that will convert the UART protocol to output states. You may connect these outputs with inputs on CC2530.
