### ISSUE TITLE
Read 7 Segment Display

### ISSUE THREAD

**Issue by Danit2** [ptvoinfo/zigbee-configurable-firmware#133]
Is it possible to read out a 7 segment display with your firmware? 
There is everywhere a lot of 7 segment displays and it would be great when we can bring them in Z2M.

**Comment by ptvoinfo** [comment]
Sorry, but the firmware does not support these displays.

**Comment by bojanpotocnik** [comment]
@Danit2 you can connect anodes of relevant 7-segment display LEDs to inputs on your module and then process them in the e.g. Home Assistant or wherever you're sending your data.
I have done this with my garage doors, to be able to (for safety, in addition to being also connected directly to the encoder and end switches) always check the garage door state as perceived by the original control system (which displays the state on 7-segment display).
![20220407_230822](https://user-images.githubusercontent.com/4901762/177333869-cf5d2390-a7bb-4538-aa27-b1fa21425fe5.jpg)
![20220407_230815](https://user-images.githubusercontent.com/4901762/177333876-b2d6c123-264b-4b9d-b248-7a7f4541967d.jpg)

**Comment by Danit2** [comment]
@bojanpotocnik Thanks for your tip. But i want to read a 3 digit 7 segment display from my dryer. 
This work with a multiplexer. So it is not so easy to read this. 
I dont know how to bring this info in my smarthome.

**Comment by bojanpotocnik** [comment]
If I was you, I would do it using ESP32 Cam module from AliExpress and ESPHome.
Or even easier for a drier: just measure the power consumptions - when it rises above the trigger value for at least e.g. 5 minutes and then falls under the trigger value (standby) for X minutes, it has finished - that's how I did it.
