### ISSUE TITLE
Configuration for Sonoff Zigbee 3.0 Usb Dongle Plus

### ISSUE THREAD

**Issue by jairbj** [ptvoinfo/zigbee-configurable-firmware#134]
Hi friends, can anyone provide configurations for router firmware on SONOFF Zigbee 3.0 USB Dongle Plus?

**Comment by ptvoinfo** [comment]
You can find the configuration in the "Presets" folder and load it in the "File" menu.

**Comment by jairbj** [comment]
> You can find the configuration in the "Presets" folder and load it in the "File" menu.

Thank you a lot. I didn't see there is a "Sonoff Dongle Pluss" preset, I Just saw the other files.

**Comment by ptvoinfo** [comment]
Hmm. I've checked the latest version. The "sonoff_3_usb_dongle_plus.ini" file is there.

**Comment by jairbj** [comment]
> Hmm. I've checked the latest version. The "sonoff_3_usb_dongle_plus.ini" file is there.

Yes it's there. It was my fault. 

Thank you a lot

**Comment by jairbj** [comment]
Yes it's there, it was my fault.

I just didn't see at the first time.

Thank you.
