### ISSUE TITLE
Добавить поддержку OTA обновлений прошивки

### ISSUE THREAD

**Issue by almirus** [ptvoinfo/zigbee-configurable-firmware#136]
Добрый день. Zigbee2mqtt поддерживает возможность OTA обновлений (в том числе можно указать свою прошивку)
Было бы круто поддержать такую возможность в прошивке, один раз прошив через программатор, последующие прошивать по воздуху

**Comment by ptvoinfo** [comment]
Sorry, but it is not possible without an external flash module. I didn't see DIY modules that have this flash module yet.
