### ISSUE TITLE
Curtain controller 

### ISSUE THREAD

**Issue by dido8884** [ptvoinfo/zigbee-configurable-firmware#139]
make it possible to bind the output to the input with blocking, this is necessary to connect the limit switches.  If the limit switch at the input is triggered, it will block the control of the communication output.  Esphome has an algorithm and implementation called endstop cover.  the only thing that can be added is an emergency entrance on which all control is blocked.  drivers have such outputs, they work when the current exceeds the setting.  well, it is possible to adjust the travel time without flashing.  Thank you for your work. https://esphome.io/components/cover/endstop.html

**Comment by dim6003** [comment]
Interested in this as well. Thanks.
