### ISSUE TITLE
Model information ignored

### ISSUE THREAD

**Issue by jsbrich** [ptvoinfo/zigbee-configurable-firmware#140]
I set the Manufacturer ID, Manufacture Name, and Model ID as shown.
![image](https://user-images.githubusercontent.com/63560376/187273378-0094e505-4039-4443-baa5-c43c89467d9a.png)

But when it connects to Zigbee2MQTT, it shows a completely different set of information for these
![image](https://user-images.githubusercontent.com/63560376/187273547-bf46334b-6b72-489f-aa45-c5d14f3eab4a.png)

Device Type was set as "End device without routing", but it is listed as a router in Z2M.

**Comment by ptvoinfo** [comment]
1. Delete the device in Z2M
2. Restart Z2M
3. Join the device again.
