### ISSUE TITLE
Request: generate custom DDF file for Deconz

### ISSUE THREAD

**Issue by WhistleMaster** [ptvoinfo/zigbee-configurable-firmware#145]
Hi !

Thanks for the great work on this firmware ! I was wondering if, as it is the case for Z2M, you could implement a button that would enable to save a [custom DDF](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) file to use with Deconz.

Regards,

WM

**Comment by ptvoinfo** [comment]
Added 2023-08-07
