### ISSUE TITLE
Changes to Model ID and Manufacture have no effect

### ISSUE THREAD

**Issue by cowana** [ptvoinfo/zigbee-configurable-firmware#146]
I am hoping to add multiple PTVO devices to my Z2M/HA system, each configured differently (using a different external converter file).

That requires each to have a different Model ID (representing the IO configuration).

I have tried changing it in the Firmware Configuration tool: 
![PTVO](https://user-images.githubusercontent.com/5606608/192648029-0eb6f711-1f6e-4e84-9e87-ee50f4ebbc38.png)

However when added to Zigbee2MQTT (in Home Assistant), the Manufacturer and Model ID always come up as the default:
![Z2M](https://user-images.githubusercontent.com/5606608/192648164-32d81f0e-63b4-40b4-b512-e386a67f39be.png)

I have tried reading back the settings from the firmware file (which verifies the modified config is there), as well as removing the device from Z2M (and restarting both Z2M and Home Assistant), then repairing. No matter what I try, the devices always identify as ptvo.switch.

I believe this could be a bug in the Firmware Configuration tool?

Many thanks for any investigation you can do.

**Comment by cowana** [comment]
After some more investigation, it seems that this may have something to do with a previous External Converter file within Home Assistant somehow modifying the Model ID to the previous value. I'm still working on getting to the bottom of it, but it appears less likely to be a firmware issue!

**Comment by ptvoinfo** [comment]
You should delete device in Z2M, restart Z2M and rejoin your device again. Z2M should display the new ModelId.
