### ISSUE TITLE
Battery voltage incorrect PSM mode

### ISSUE THREAD

**Issue by krisztian0willinger** [ptvoinfo/zigbee-configurable-firmware#150]
Hi,

I'm using the 2022-10-22 version to create a firmware for my CC2530 modules.
In PSM mode the battery status is sent now in the newest version but it is incorrect. The firmware is sending battery: 100 and voltage: 3400 regardless of the power supply voltage. I tried voltages between 2.5V - 3.3V
Do you know what can be the issue?

**Comment by ptvoinfo** [comment]
I cannot confirm it. I've tested the firmware with 2.5 and 3.0V. It reports voltage correctly.
