### ISSUE TITLE
CC2530 as push button

### ISSUE THREAD

**Issue by tecnicoguion** [ptvoinfo/zigbee-configurable-firmware#154]
Hello, I am trying to configure an XL2530-D01 with a final device, powered by a cr2032 battery, to configure an input as a pushbutton, but when I link it to the Home Assistant through ZHA it does not appear that it has any input. Is there any way to configure it?
Thank you

**Comment by ptvoinfo** [comment]
Hi, 

Could you please show your configuration? Did you create a custom converter for your device and add it to Z2M?
