### ISSUE TITLE
Can't remotely change number of  LEDs (CC2530+CC2592)

### ISSUE THREAD

**Issue by DJTerentjev** [ptvoinfo/zigbee-configurable-firmware#157]
Please see attached configuration file. Can't remotely change the number of LEDs. I tried changing in the web interface of Z2M (Home Assistant) and send command to the topic: zigbee2mqtt/0x00124b001ec71cb2/l5/set
![image](https://user-images.githubusercontent.com/1267473/201543252-4f4f6fd4-bd99-4d0b-bba1-f5133c86070b.png)

Configuration file: [z_led.txt](https://github.com/ptvoinfo/zigbee-configurable-firmware/files/9998146/z_led.txt)

**Comment by ptvoinfo** [comment]
Did you reboot your device after the configuration change?

**Comment by DJTerentjev** [comment]
No. I didn't. You are correct. If number of LED was changed, device have to be reset or power off and on. I was expected to change on the 'fly' 👍 .  Could you please mention it on your site in the remote configuration section. Also please correct information on the site. Right topic is zigbee2mqtt/[friedly_name]/set/[channel]. Thanks.
