### ISSUE TITLE
Can't change the color if LED strip is configured on Output other than one.

### ISSUE THREAD

**Issue by DJTerentjev** [ptvoinfo/zigbee-configurable-firmware#158]
Please see configuration. If LED strip is set on the Output other than one, can't change the colors, same time can change bigness  and on/off. With Output one it works, but I dot's want to use Input 1, as it can reset the device. 

![image](https://user-images.githubusercontent.com/1267473/201544091-bb7327a0-1b0d-4f0e-be11-1455496863bf.png)

Configuration file: [z_led.txt](https://github.com/ptvoinfo/zigbee-configurable-firmware/files/9998189/z_led.txt)

**Comment by ptvoinfo** [comment]
@DJTerentjev It seems that it is a bug if Z2M frontend. You can change the color from MQTT explorer if you send a command like:

Topic: z2m/0x00124b0022055177/set

JSON: {"color_l2":{"hex":"#FFFF41"}}
