### ISSUE TITLE
RFX2401 PA Control pins not restored after reading settings from firmware

### ISSUE THREAD

**Issue by ICTSMART** [ptvoinfo/zigbee-configurable-firmware#16]
When setting up the firmware for use with the EBYTE E18-MS1PA1 it looks like the corresponding .txt file saves the setting. Nevertheless, this setting is not restored after pressing the 'read settings from firmware' button.

**Comment by ptvoinfo** [comment]
Fixed in the latest version.
https://ptvo.info/download/cc2530_io_1.2.2a.44539_firmware.zip?q=1610631088
