### ISSUE TITLE
Endpoints changed spontaneously

### ISSUE THREAD

**Issue by byka-org** [ptvoinfo/zigbee-configurable-firmware#161]
I use cc2530 chip with PTVO firmware. 
Initially configured Endpoint1 as DS18B20 sensor, Endpoint2 as Counter. All works fine about a month.
Power source is stabilized, no breaks, no reboot, clear 3.3V all time.

But once something was changed: now DS18B20 sensor sit on Endpoint2, and Endpoint1 disappeared.
And temperature sensor works fine, but on wrong endpoint.

How it can may be?
It is not a coordinator issue, as I can see (raw data at coordinator debug log), but why endpoints changed and how it possible?
I can re-flash device, but what if that will be repeat again?

**Comment by ptvoinfo** [comment]
Hi @byka-org,

It is almost impossible. The device configuration is hard-coded in the firmware. I can only see one theoretical possibility, if your device flash memory is damaged.
