### ISSUE TITLE
LED firmware. Controlling Colour Temperature.

### ISSUE THREAD

**Issue by DJTerentjev** [ptvoinfo/zigbee-configurable-firmware#168]
Thank you for your effort to crate and constantly develop this firmware. It's probably easies way to create DIY ZigBee devises . Could you please add control for light temperature for RGB+CCT light with two PWM outputs.

![image](https://user-images.githubusercontent.com/1267473/209218139-4fb7cd07-11e4-40db-8ce3-bdd899d78406.png)

**Comment by ptvoinfo** [comment]
@DJTerentjev Sorry, but I don't have the corresponding device for testings and don't know how it should work.

**Comment by DJTerentjev** [comment]
This option was added to configurator. Thank you!

**Comment by 24021438** [comment]
I want to make a dual color temperature lamp, but I don't know how to set the color temperature channels L1L2, e.light_ brightness_ Colortemp (). withEndpoint ('l2 '), including brightness control. How do I fill in the channel control of two L1L2 channels? e.light_ brightness().withEndpoint('l2')

**Comment by 24021438** [comment]
I want to make a dual color temperature lamp, but I don't know how to set the color temperature channels L1L2, e.light_ brightness_ Colortemp (). withEndpoint ('l2 '), including brightness control. How do I fill in the channel control of two L1L2 channels? e.light_ brightness().withEndpoint('l2')

**Comment by ptvoinfo** [comment]
@24021438 Please load the "gledopto" configuration file from the "Presets" folder.
