### ISSUE TITLE
Linked push button with double, tripple and long push report

### ISSUE THREAD

**Issue by Arthuret** [ptvoinfo/zigbee-configurable-firmware#169]
Hello,
I would like to use this firmware inside a wall push button, between the buttons and lamps, to be able to control the lamps through the button or zigbee, but also get zigbee reports on double, tripple and long presses, without affecting the connected lamp.
Would it be possible to link an output only on the simple push when selecting double, tripple and long ?
Thanks

**Comment by ptvoinfo** [comment]
@Arthuret Could you please test the latest version where I've added this feature?
