### ISSUE TITLE
SONOFF SNZB-01 not working!!!

### ISSUE THREAD

**Issue by bummer52** [ptvoinfo/zigbee-configurable-firmware#171]
Hi.
I have a SONOFF SNZB-01 button. I bought the premium version of the program. I made a firmware for him. When in the Device type is select (End device vithout route), everything works as it should, when Device type is select (power saving mode), it does not connect to the zigbee network at all.
P.S. In my premium version of programm is 8 inputs and outputs not a 16. its normally?

**Comment by ptvoinfo** [comment]
Hi,

1. Could you please show me your settings? Did you try to place this button closely to the coordinator? Please note, the firmware tries to connect about 1 minute. You need to press a button periodically, to extend this interval.
2. The PSM firmware supports 8 channels only. There is the separate "16-channel" version.

**Comment by bummer52** [comment]
![Screenshot 2023-01-15 130234](https://user-images.githubusercontent.com/115506233/212536994-add32d8f-f31a-4344-af14-1f404b5e53e5.png)
![Screenshot 2023-01-15 130306](https://user-images.githubusercontent.com/115506233/212536999-f17429d1-f33d-46a4-96d6-d7b45844f700.png)
Button placed from coordinator aprox 50cm. Why button with end device setting conect to coordinator ~10sec

**Comment by ptvoinfo** [comment]
Could you please try to select the "CC2530 (without external oscillator)" board type?

**Comment by bummer52** [comment]
I combine ptvo firmware with efekta converter and that work fine. this option work "CC2530 (without external oscillator)"
