### ISSUE TITLE
Add support for timer

### ISSUE THREAD

**Issue by fensoft** [ptvoinfo/zigbee-configurable-firmware#174]
Like a timer button, when "on message" is sent, the output will be set to off x sec later.
If another "on message" is sent, timer is reset.

**Comment by ptvoinfo** [comment]
@fensoft Do you mean the "On" message when the timer is still active?

**Comment by fensoft** [comment]
Yes.

If time is 60s:

Press on-> wait 60s->Auto off
Press on->wait 30s->press on->wait 60s->auto off

**Comment by ice2009** [comment]
Hello it possible make timer how ask user on up? for the switch and gpio ?

**Comment by ptvoinfo** [comment]
@ice2009 Sorry, but I didn't understand your question.

**Comment by ice2009** [comment]
i See you add timer to pulse switch . Switch turn off automaticly. It possible change seconds to miliseconds?

**Comment by ptvoinfo** [comment]
@ice2009 No, this timer can measure seconds only. You can implement short timers using the "trigger" command (https://ptvo.info/zigbee-configurable-firmware-features/gpio/).
