### ISSUE TITLE
Firmware 1.8.0.7 not working with CC2652RB

### ISSUE THREAD

**Issue by CSRLabs** [ptvoinfo/zigbee-configurable-firmware#176]
Latest firmware 2023-01-12 ver. 1.8.0.7 seems to break support for CC2652RB device.
The same hardware and same configuration works fine with previous firmware 2022 1.7.3.0.

Symptoms: the status led does not turn on and the UART tx output is fixed at logic state 1

<img width="496" alt="ptvo-issue" src="https://user-images.githubusercontent.com/121581941/215279077-7aee7472-f0c0-44a2-a908-8c743709d603.png">

**Comment by deaxx** [comment]
connect the quartz to the module and flash the firmware for cc2652r
![IMG_20230128_225350_181](https://user-images.githubusercontent.com/28512561/215283247-00481448-2944-4d6e-8105-50dd98759805.jpg)

**Comment by CSRLabs** [comment]
@deaxx so you mean that newer firmware requires an external quartz to work?
This is not clear to me.
Please notice that previous firmware version works fine without any external quartz.

**Comment by deaxx** [comment]
this is a way to make the module work on this particular version

**Comment by CSRLabs** [comment]
I'll wait for the next fw version and hope this will be fixed.

**Comment by ptvoinfo** [comment]
@CSRLabs Could you please test the latest release? I've resolved the issue with CC2652RB.

**Comment by CSRLabs** [comment]
I confirm it is working fine now. Thank you for the quick fix.
I will keep the device monitored in the coming days just to make sure it is working as expected.
