### ISSUE TITLE
Read settings from firmware is not working

### ISSUE THREAD

**Issue by mojijafari** [ptvoinfo/zigbee-configurable-firmware#18]
Dear ptvoinfo,

Thank you very much for your amazing project. I appreciate your kind effort. however, the read setting from firmware button is not working for me. could you help me for that?

**Comment by ptvoinfo** [comment]
Hello.

Did you create the firmware file using my utility before?

**Comment by mojijafari** [comment]
No, I did not, but as I am amature, I just want to know the configuration of others. I tried other hex files and can't open with your amazing program.

thank you

**Comment by ptvoinfo** [comment]
I thought it is obvious that my utility can read the settings of my firmware only :).
