### ISSUE TITLE
Setting brightness via custom converter doesn't work, but default ptvo.switch does

### ISSUE THREAD

**Issue by mortenmoulder** [ptvoinfo/zigbee-configurable-firmware#181]
Really standard LED strip setup with a WS2812b strip: 

![image](https://user-images.githubusercontent.com/1304665/219816319-321cef3b-33e5-43f3-ad8e-e7e087e128a2.png)

When using that together with a custom converter for Zigbee2MQTT, I get this UI:

![image](https://user-images.githubusercontent.com/1304665/219816373-27429d1c-619a-4156-96bc-db07931d46d7.png)

The brightness slider does not work. When I set it to any number, this is what happens:

```
Debug 2023-02-18 00:33:14Received MQTT message on 'zigbee2mqtt/zig-led-v1/set' with data '{"brightness_l1":63}'
Debug 2023-02-18 00:33:14Publishing 'set' 'brightness' to 'zig-led-v1'
Info 2023-02-18 00:33:14MQTT publish: topic 'zigbee2mqtt/zig-led-v1', payload '{"brightness_l1":39,"color":{"x":0.1724,"y":0.7468},"color_mode":"xy","device":{"applicationVersion":1,"dateCode":"2023-02-18","friendlyName":"zig-led-v1","hardwareVersion":1,"ieeeAddr":"0x00124b002a5f2ea8","manufacturerID":4447,"manufacturerName":"smarthjemmet.dk","model":"zig-led-v1","networkAddress":22024,"powerSource":"Mains (single phase)","softwareBuildID":"2023-02-18","stackVersion":1,"type":"EndDevice","zclVersion":1},"l2":0,"l3":1,"l4":10,"last_seen":"2023-02-18T00:33:14+01:00","linkquality":153,"state_l1":"ON","state_l2":"OFF","state_l3":"OFF"}'
```

However, when I just use the default `ptvo.switch` custom converter, the MQTT command is:

```
topic: zigbee2mqtt/0x00124b002a5f2ea8/set
payload: {"l3":255}
```

And that works. I just input 255 in the UI like this (it should be off, but the device is disconnected):

![image](https://user-images.githubusercontent.com/1304665/219816857-d862c56b-e660-4ca7-9ca4-d46b494fd9c1.png)

Is this a bug in the "Save custom converter" functionality, or am I just supposed to write my own converter? 😄

**Comment by ptvoinfo** [comment]
L3 is designed to automatically change brightness. When you write the analog value to L3, you change an interval.

You should change the brightness on L1. Can you change a color there?
