### ISSUE TITLE
Use Sonoff SNZB-01 for bistable swich

### ISSUE THREAD

**Issue by robotsflo** [ptvoinfo/zigbee-configurable-firmware#182]
Hello,
Did you think that is possible to flash with custom firmware a cheap Sonoff SNZB-01 push button to do the same functionnality that an [hue wall switch](https://www.philips-hue.com/en-gb/p/hue-philips-hue-wall-switch-module/8719514318045) 
I would like to send "Toggle" command each time that i press on a bistable rocker switch 
Most of manufactured device use basic push button. 
Today, in my experience, only the "hue wall switch" have this feature but is expensive.

Thanks a lot for your reply.

![image](https://user-images.githubusercontent.com/32175029/220417257-df180b54-52b5-4e16-910f-4ac594c4cbdf.png)
![image](https://user-images.githubusercontent.com/32175029/220417452-60d07275-d21d-4bb2-a154-9757bec10021.png)
![image](https://user-images.githubusercontent.com/32175029/220417547-55ff1990-050b-4ac8-a9a3-ea216b969224.png)

**Comment by ptvoinfo** [comment]
@robotsflo 
You can try to select "Switch" + "Toggle" + Bind command "Toggle" for "Input".

**Comment by robotsflo** [comment]
Info : 
P1.0 : led pin 
P1.5 : Main push button
P2.0 : Reset push button
![image](https://user-images.githubusercontent.com/32175029/221586451-747bb55a-6b6c-4db5-a999-79b5532d036a.png)
