### ISSUE TITLE
e18-ms1-pcb + bme280 PSM

### ISSUE THREAD

**Issue by bachy** [ptvoinfo/zigbee-configurable-firmware#183]
Hi,

i'm trying to setup a temp sensor PSM end device with e18-ms1-pcb chip coupled with a bme280 but current consumption stay way to high: 44mA in active and 16ma between reports

I can't figure out why

here are my ptvo conf, schematics and pcb design
![Screenshot_20230226_221058](https://user-images.githubusercontent.com/1004813/221437768-7fa6c214-ae1f-4ffa-9e7a-bd82adb4bfb4.png)
![Screenshot_20230226_221137](https://user-images.githubusercontent.com/1004813/221437772-c90dc687-5c7a-452f-bb7a-ee9e9c70cf23.png)
![Screenshot_20230226_221222](https://user-images.githubusercontent.com/1004813/221437776-26472330-eea2-482f-95ce-dca9f8d2ab69.png)
![Screenshot_20230226_221419](https://user-images.githubusercontent.com/1004813/221437778-1925c830-b677-49a9-8f90-f175a81b5301.png)

any idea ?

**Comment by ptvoinfo** [comment]
@bachy Hi, I do not see external pull-up resistors in your schematic.

**Comment by bachy** [comment]
Hi, thank you for your answer !

this is my bme280 board, it has pullups, right ?
![bme280](https://user-images.githubusercontent.com/1004813/221559794-880a31eb-3392-4e22-b54f-8039e10a11ce.jpg)

i powered the bme280 board directly to vcc and disabled "external sensor power" 
![Screenshot_20230227_130001](https://user-images.githubusercontent.com/1004813/221560107-db511c71-a26e-4502-ac8e-eef33f39356b.png)
![Screenshot_20230227_130029](https://user-images.githubusercontent.com/1004813/221560120-f060f80b-202d-4426-8cb5-94f0f1a8f7a4.png)

it is better but i steel have 27mA active and 200µA in power saving mode, wich seems still to much to me, no ?
i should have only a few µA when sleeping ?

**Comment by ptvoinfo** [comment]
OK. Could you check power consumption without BME attached? Maybe, there is a current leak in another place?

**Comment by bachy** [comment]
bme280 totaly detached, the circuit consume 1µA

**Comment by bachy** [comment]
ok, it seems to be good, i re-attached the bme, and once repaired to z2m it consume 1.1µA in sleepmode and 8mA when sending data

all goods ! thanks

could you explained why the "external power sensor was not working ?

**Comment by ptvoinfo** [comment]
It works with some sensors. In some cases, it requires a special power control circuit. 
You can also try this output type with internal pull-up or pull-down resistors.
