### ISSUE TITLE
[Feature Request] Custom mapping of battery percentage in PSM devices

### ISSUE THREAD

**Issue by CSRLabs** [ptvoinfo/zigbee-configurable-firmware#185]
It would be nice to have the capability to map 0% and 100% of battery percentage to custom voltages so that different types of batteries can be properly monitored in PSM firmware.
I believe this should be easy to implement in the GUI.

**Comment by ptvoinfo** [comment]
The firmware can report battery voltage. You can handle it in a higher level system and create the necessary mapping.
