### ISSUE TITLE
[Vote] HX711 sensor.  Vote who needs it too.

### ISSUE THREAD

**Issue by ikey-ru** [ptvoinfo/zigbee-configurable-firmware#186]
Рассмотрите пожалуйста возможность добавить популярную микросхему для тензодатчиков HX711.
Год назад Philip тоже просил:
<img width="876" alt="Снимок экрана 2023-03-08 в 21 34 19" src="https://user-images.githubusercontent.com/47115676/223805291-75f593a4-04e1-4124-913a-c5c097ad6541.png">

Кому тоже нужно, пожалуйста, проголосуйте.

**Comment by dido8884** [comment]
Да, идея нормальная, к этим платам можно подключить датчик давления резистивный.

**Comment by Boolkinator** [comment]
👍

**Comment by Garkus98** [comment]
+

**Comment by cat-inGlasses** [comment]
👍

**Comment by pxbiuibiu** [comment]
👍

**Comment by LimeQuat** [comment]
+

**Comment by epvdvalk** [comment]
Would like that!

**Comment by francisbesset** [comment]
:+1:

**Comment by darkside9009** [comment]
please add HX711 :-)

**Comment by francisbesset** [comment]
@ptvoinfo I see that HX711 is available for CC2652 and CC1352 only.
Do you think will be available in further for CC2530?

Thank you very much for your work.

**Comment by ptvoinfo** [comment]
@francisbesset There is no free flash memory for new features. Therefore, I add them for new chips (CC2652 and CC1352) only.
