### ISSUE TITLE
Add ability for making BSL firmware

### ISSUE THREAD

**Issue by SlyFoxeh** [ptvoinfo/zigbee-configurable-firmware#189]
Since some old cc2531 already flashed with SBL firmware and can be reflashed via serial boot tool, please make possibly to rebuild firmware for Serial Boot Tool
For IAR that’s https://www.waveshare.net/w/upload/d/da/Serial_Boot_Loader_for_CC253x.pdf

**Comment by ptvoinfo** [comment]
Sorry, but there is no free space for BSL in CC2530 and CC2531. My firmware is too large.
