### ISSUE TITLE
Four switch inputs with PSM

### ISSUE THREAD

**Issue by Flavien** [ptvoinfo/zigbee-configurable-firmware#191]
When trying to configure four switches like this:

![image](https://user-images.githubusercontent.com/296540/226768874-3710be27-8467-40f4-aede-acdb2469dd35.png)

I get the following warning:

![image](https://user-images.githubusercontent.com/296540/226768907-c744e07f-8d72-476e-910d-df73d1de7bff.png)

The page about PSM notes that:

> The CC2530 has a hardware limitation of this implementation. You can add only one switch on pin ranges P00..P07, P10..P13, P14..P17, P20..P23. Therefore, you can have up to four switches in your configuration.

This is contradicted by the error message which seems to indicate you can't have more than 3 switches with PSM (not 4).

Which one is correct?

**Comment by ptvoinfo** [comment]
Please ignore this warning message. Your settings are correct.
