### ISSUE TITLE
SHTC3 sleep mode

### ISSUE THREAD

**Issue by turboproc** [ptvoinfo/zigbee-configurable-firmware#192]
Wondering whether in PSM mode, the SHTC3 is put into sleep mode between measurements. Reason for asking is that in between measurements the total drawn current is still 30-40 uA which is definitievely more than what one would expect with the CC2530 an SHTC3 both in sleep mode.
In case the SHTC3 sensor is not put into sleep mode, would it be possible to add?

**Comment by ptvoinfo** [comment]
The firmware uses the "Single shot" mode for this sensor in the PSM mode. Probably, this rather high current is related to unwashed flux on your CC2530 module or other wires. Did you check power consumption without the sensor?
