### ISSUE TITLE
I created a two way pwm and I want to set it to cw

### ISSUE THREAD

**Issue by 24021438** [ptvoinfo/zigbee-configurable-firmware#194]
I want to make a dual color temperature lamp, but I don't know how to set the color temperature channels L1L2, e.light_ brightness_ Colortemp (). withEndpoint ('l2 '), including brightness control. How do I fill in the channel control of two L1L2 channels? e.light_ brightness().withEndpoint('l2')

**Comment by ptvoinfo** [comment]
@24021438 Please load the "gledopto" configuration file from the "Presets" folder.

**Comment by 24021438** [comment]
First of all, thank you for your answer. The first time I used this firmware, I have already mastered the switch firmware, but I can't figure out how to generate a lamp with only cw dual channel pwm. Could you take a screenshot to demonstrate how to configure the firmware?

**Comment by 24021438** [comment]
I only need color temperature lamps with only CCT

**Comment by ptvoinfo** [comment]
@24021438 Could you please test the new feature (two PWM channels for white color temperature)?
