### ISSUE TITLE
The firmware recognizes the wrong conversion file

### ISSUE THREAD

**Issue by 24021438** [ptvoinfo/zigbee-configurable-firmware#196]
The firmware uses the Custom devices (DiY) ptvo.switch incorrect conversion file by default, it may be that I flashed the switch component before, and now I have replaced the firmware function, it now cannot change to the js file I set, but use the default ptvo

**Comment by ptvoinfo** [comment]
There are several similar issues (solved).
https://github.com/ptvoinfo/zigbee-configurable-firmware/issues?q=delete
