### ISSUE TITLE
PSM don't wake-up

### ISSUE THREAD

**Issue by axelhorn** [ptvoinfo/zigbee-configurable-firmware#198]
What am I doing wrong?
Sonoff SNZB-04 module (on ZB-DS01 v1.0 board) - simple door/window sensot with CC2530F256 chipset.
When I load the "end device" firmware to it - it works properly. When I load PSM, I force it to pair with a reset - the LED flashes from time to time for a few seconds, then it goes into a deep sleep state and cannot be woken up in any way. external wake-up, neither a sensor nor periodic reports.It doesn't matter what I set in the advanced options, after falling asleep the module stops responding.
However, if after pairing I press the external wake-up (input1) button every few seconds, preventing him from falling asleep, the module flashes but does not pair.

![obraz](https://user-images.githubusercontent.com/73194444/233487645-822d7708-daab-4fb4-9e4b-d14cbc03a5ff.png)
![obraz](https://user-images.githubusercontent.com/73194444/233487720-17614017-92f8-4069-97cf-acba1df49629.png)

**Comment by ptvoinfo** [comment]
@axelhorn 
Sorry, but I don't know anything about a schematic of this device. Are you sure about "External pull-up" and "Inversed" for "Input 1"?

**Comment by axelhorn** [comment]
Yes, GPIO 2_0 is pulled up by resistor to +battery and button switches do ground.

**Comment by ptvoinfo** [comment]
Then you should disable "Inversed" for "Input 1".

**Comment by axelhorn** [comment]
No combination helps.
However, reading the documentation from the CC2530, I see that a 32kHz crystal oscillator is needed on the XOSC32K inputs to wake up from sleep mode by the timer. Can you confirm if the oscillator is necessary for your PSM firmware or if I understand it correctly because 
I'm not sure. Because this Sonoff module does not have such an oscillator. It only has the main 32MHz.
![IMG20230422214442](https://user-images.githubusercontent.com/73194444/233803827-63c5947f-188f-4b77-ba2a-0390cf9a9eaf.jpg)

**Comment by deaxx** [comment]
> No combination helps. However, reading the documentation from the CC2530, I see that a 32kHz crystal oscillator is needed on the XOSC32K inputs to wake up from sleep mode by the timer. Can you confirm if the oscillator is necessary for your PSM firmware or if I understand it correctly because I'm not sure. Because this Sonoff module does not have such an oscillator. It only has the main 32MHz. ![IMG20230422214442](https://user-images.githubusercontent.com/73194444/233803827-63c5947f-188f-4b77-ba2a-0390cf9a9eaf.jpg)

Use this config
![2233](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/28512561/01c75be9-91c8-4a45-9584-a8f67ebadc29)

**Comment by axelhorn** [comment]
Alleluyah! :) It's working. Sonoff ZB-DS01 open door sensor works with this configuration. Additionally, so far it seems to run more stable on the ptvo firmware than on the original Sonoff firmware.
