### ISSUE TITLE
Feature Request: OTA update ?

### ISSUE THREAD

**Issue by grostim** [ptvoinfo/zigbee-configurable-firmware#2]
Hi !

First of all, thank you for the good job.

I'm probably dreaming awake, but i was wondering if OTA update would be doable for your customizable firmware ?

**Comment by ptvoinfo** [comment]
Hi, 

Unfortunately, there is no free memory for OTA.

**Comment by bojanpotocnik** [comment]
Is this still true for CC2652?

**Comment by ptvoinfo** [comment]
@bojanpotocnik It is true only if you have an external flash memory ~1MB.
