### ISSUE TITLE
Running on ZigUP hardware

### ISSUE THREAD

**Issue by copystring** [ptvoinfo/zigbee-configurable-firmware#20]
Hey,

I'm trying to get this to work on my ZigUP device(s) (https://github.com/formtapez/ZigUP). The only part that matters to me is the switching of the relay.
Looking at the code of ZigUP this part seems to do the switching:
![image](https://user-images.githubusercontent.com/1298861/105643267-20e2c980-5e8f-11eb-9d89-860df7152015.png)

Can this be recreated with this firmware? I tried but failed.

**Comment by ptvoinfo** [comment]
Hello. No problems. You should add a bi-stable relay with these pins.
https://ptvo.info/zigbee-configurable-firmware-features/bistable-relay/
Timeouts: 50 ms.

**Comment by copystring** [comment]
Yeah. I thought so and tried that. Maybe I misunderstand this?
Is this correct?
![image](https://user-images.githubusercontent.com/1298861/105749440-b2ac0e80-5f43-11eb-8dce-fa9f8b3c6c73.png)

**Comment by ptvoinfo** [comment]
1. Disable Input1 
2. Change Output1 to P11
3. Change Output2 to P12

**Comment by copystring** [comment]
Nice. This worked. So the underscore is not a dot then. I thought P1_1 = P1.1 :)  Thank you very much!

**Comment by ptvoinfo** [comment]
You are welcome!
