### ISSUE TITLE
CC2530 internal pull-up resistor seems not enabled in later versions of ptvo

### ISSUE THREAD

**Issue by Goodwillson** [ptvoinfo/zigbee-configurable-firmware#200]
I am not sure if this is not some settings issue, but I cant figure it out. I did a test with older version of ptvo firmwave (2021-07-05) and also latest versions 2023-02-07 & 2023-04-22. Both never versions behave same way with same setup. GPIO pin set as switch mode, seems to not have enabled pull up resistor, because when I watch zigbee2mqtt messages, it gets triggered by random noise, the longer the sensor cable, the more frequently it triggers, which is not the case with old ptvo version. I am doing the test on P05 pin with reed switch as in scheme. 
![image](https://user-images.githubusercontent.com/46995056/233937414-3405c83d-f5ac-4036-b98b-9259a3ce4fe5.png)

The configuration and behaviour comparison of old and new firmwave setup is on following image. Left is the old firmware setup and state_l5 graph from mqtt explorer, on the right is latest ptvo firmware setup and state_l5 graph, which is full of false triggers.

![image](https://user-images.githubusercontent.com/46995056/233938797-e910ecca-1d8c-486f-9e45-1c45eb91717c.png)

I couldnt find on your site any further documentation about the setup of newer firmware, if there is any difference to older one, nor any other people with similar issue. The setup was taken from [https://community.home-assistant.io/t/diy-zigbee-weather-station/378652](https://community.home-assistant.io/t/diy-zigbee-weather-station/378652).

**Comment by ptvoinfo** [comment]
@Goodwillson It seems that this issue it related to an incompatibility of ADC and GPIO with an internal pullup resitor on the same port (P0x).  If it is possible, add external pullup resistors and re-configure GPIO P00, P07, P05. Or move these GPIO to P1x.
