### ISSUE TITLE
ptvo.info website down

### ISSUE THREAD

**Issue by AreSanito** [ptvoinfo/zigbee-configurable-firmware#205]
Hello,
I don't know how to contact you so I'm posting here, your website seems down.

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/24324917/26b7828a-3fd4-4bef-bfa0-a94e364bd1ee)

Thank you for your work.

**Comment by ptvoinfo** [comment]
Restored. Thank you!
