### ISSUE TITLE
Inputs not doing anything in Home assistant (ZHA). Outputs work

### ISSUE THREAD

**Issue by alfi666** [ptvoinfo/zigbee-configurable-firmware#206]
Hi all,
I'm trying to create a simple 4x binary input zigbee device - basically like 4x door/window contacts.
I want them to show "closed" whenever they are shorted to the GND, but as soon as disconnected, it should show "open"

I configure 4 GPIO as inputs with internal Pull-up, however they are still showing as "closed" in Home assistant - regardless if I short them to GND or not.
If I link the inputs to outputs - then the outputs are switching on/off, but what is the point to have the "input" sensors?

What am I missing? Why is HA not showing the actual state of the INPUT?
![HA](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/19765958/ddf9208a-3b1e-4048-bbc7-f99b4c6b79ac)
![ptvo](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/19765958/88ae0e7c-656b-478f-830c-a1667fc3650c)

**Comment by ptvoinfo** [comment]
@alfi666 Did you create and add a custom converter for this device (on the Experts tab)?

**Comment by alfi666** [comment]
> @alfi666 Did you create and add a custom converter for this device (on the Experts tab)?

Hello - I did not... not sure what it is and what it does :(
Do I need to "Save custom converter to Z2M"? What would I then used that *.js file for?
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/19765958/e5c074b9-c123-4c27-81ab-2c7940353082)

**Comment by alfi666** [comment]
> @alfi666 Yes, you should use this button. Please look here: https://ptvo.info/zigbee-configurable-firmware-features/expert/

OK, I read thru this, but this seems specific to Zigbee2MQTT - but I’m not using that. 
I’m using the ZHA implementation in Home assistant.

Does it mean then the issue is with ZHA implementation and it is not recognizing the inputs correctly?

**Comment by alfi666** [comment]
Fair enough - I’ll try and investigate on HA group if there’s any workaround

**Comment by garubi** [comment]
@alfi666 have you found any solution?
I'm in the same boat too, using ZHA, my device shows up but with neither output nor input dispalyed in HomeAssistant.

If you want we can join our efforts in investigating ;-)

My understanding (but I could be completely wrong) is that the Zigbee2MQTT _custom converter_  is the equivalent of the ZHA _quirk_ : it could be that one have to write a custom _quirk_ to allow Home Assistant to understand and display the sensors...
see, for example,

- https://github.com/zigpy/zha-device-handlers/issues/416 
- https://github.com/zigpy/zha-device-handlers/issues/1851 (lot of informations, but I still have to _digest_ them )

**Comment by alfi666** [comment]
@garubi Hello, no I have not found a solution, but I think you're right - it probably could be fixed by ZHA quirk - however I have not had time to deep dive into it yet.
So far I have configured the PTVO firmware as on my screenshot and this way I have outputs which react to input. Given I only need 4 input and don't need output, it works for me like that - I just need to track the state of outputs in HA instead of inputs.

**Comment by garubi** [comment]
@alfi666 well done!
Maybe in the next weeks I'll try to understand the quirks syntax... 
Inthe meantime, to solve my urgent need (lot of WAF factor here... ) I swiched to an ESP32 with EspHome... but really hate to have IOT devices on Wifi...
