### ISSUE TITLE
Example configuration

### ISSUE THREAD

**Issue by mojijafari** [ptvoinfo/zigbee-configurable-firmware#21]
Could you please share us some example configurations like zigbee wall switch or cordinator or rooter etc.?
It would be very useful to understand the model of configuration.

Thank you in advance

**Comment by ptvoinfo** [comment]
This firmware cannot work as a coordinator. The router function works automatically. The wall switch configuration depends on your schematic.

**Comment by mojijafari** [comment]
do you have a sample shematic of wall switch. I just want to understand the configuration.

**Comment by ptvoinfo** [comment]
Published several examples:
https://ptvo.info/zigbee-configurable-firmware-features/diy-examples/
