### ISSUE TITLE
Backup functionality with Sonoff zbmini for smart bulbs

### ISSUE THREAD

**Issue by finwes** [ptvoinfo/zigbee-configurable-firmware#210]
First of all, I want to congratulate you and thank you for all the work done on this firmware.

I am redoing the house lighting installation, and I want to automate all the switches (around 30 of them). I have been looking at various alternatives, and at first glance, it seems that the Sonoff zbmini fits almost all my needs (version with neutral wire). There is one specific thing it doesn't do, but I find it highly necessary. I was wondering if it would be possible to achieve this behavior with your firmware. What I'm looking for is when the relay is connected to a smart bulb, the switch does not directly activate the relay, but only sends a message to the coordinator, and then the bulb is operated through automations. However, if the relay is not connected to the coordinator (due to it being turned off, malfunctioning, or intentionally disconnected), then it should directly control the relay. This way, the installation would work with smart bulbs, but in case of coordinator failure, it would still function by cutting off the power to the bulbs as if they were regular bulbs. Something like a "Conditional Link to out x" setup would be great. Where the conditions could be "coordinator reachable" and "coordinator unreachable". This behavior can be achieved with the Sonoff mini, WiFi version, flashed with ESPHome. However, I am not considering WiFi solutions for this application at the moment.

If you think that there is other hardware (that can act as a router) that can offer better functionality at a similar price, I'm still open to considering it.

Thank you very much in advance for your help.

**Comment by ptvoinfo** [comment]
Sorry, but this functionality is not available.
