### ISSUE TITLE
Which Zigbee stack does this firmware use?

### ISSUE THREAD

**Issue by Outsidewall** [ptvoinfo/zigbee-configurable-firmware#211]
I'm unable to find in the documentation which zigbee stack this firmware uses, nor away of contacting the developer for simple questions.

Can anyone please help

Regards John

**Comment by ptvoinfo** [comment]
Hi,
СС2530, СС2531 - ZStack 1.2
CC265x, CC135x - ZStack 3 (SDK v6.4)
