### ISSUE TITLE
Read Attribut 0x0055 of cluster 0x0012 bug

### ISSUE THREAD

**Issue by KiwiHC16** [ptvoinfo/zigbee-configurable-firmware#22]
Test: configure at least 1 Input as switch as per this exemple (4 configured here)
![image](https://user-images.githubusercontent.com/8549674/106496698-7c2f4000-64bd-11eb-9498-2539a421a036.png)

Plug a switch between GND and Pin 23 (P00). You will receive the attribut 0x0055 on EP1 each time you change the switch.

Now read the attribut 0x0055 on EP01 cluster 0012 and the answer is wrongly formatted. Value of the attribut missing:

![Capture d’écran 2021-02-01 à 18 48 00](https://user-images.githubusercontent.com/8549674/106497179-04ade080-64be-11eb-99f8-1c7dcf3764ff.png)

![Capture d’écran 2021-02-01 à 18 48 20](https://user-images.githubusercontent.com/8549674/106497230-0f687580-64be-11eb-8056-30120cbae425.png)

Status : 00 -> Ok
Attribut Type 20: which in 8Uint while the norm talks about 16bit type
Value: missing

I get the issue with the sniffer and also with my GW (Zigate).

Could you have a look ?

**Comment by mickadam29** [comment]
Any help is welcome

**Comment by ptvoinfo** [comment]
Fixed in the latest version.

**Comment by mickadam29** [comment]
Thank's

**Comment by KiwiHC16** [comment]
Thanks a lot.
