### ISSUE TITLE
BMP280 on v 1.9 not working

### ISSUE THREAD

**Issue by olekdata** [ptvoinfo/zigbee-configurable-firmware#225]
version 1.9.0.4

txt file
```
Board type: CC2530
Device type: Router
Update firmware's timestamp : 2023-08-29
Set default reporting interval (s): 60

Output pins:
P31: Output 1, GPIO (Role: Generic), Remember state
P06: Output 2, Temperature sensor (I2C), Pull-up (Address (dec): 119, Type: BMx280)
P07: Output 3, I2C SCL/SPI CLK, Pull-up

Input pins:
P12: Input 1, GPIO, Pull-up, Switch, Link to out 1 (Bind command: On/Off)
```
screen
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/54954537/1f02e7b0-8062-4a6b-8590-637efbc8a4ed)
not working

the same on version 1.4.11.1

txt file
```
Board type: CC2530
Device type: Router
Update firmware's timestamp : 2023-08-29
Set default reporting interval (s): 60

Output pins:
P31: Output 1, GPIO, Remember state
P06: Output 2, BMP280 (I2C SDA), Pull-up (Address (dec): 119)
P07: Output 3, I2C SCL, Pull-up

Input pins:
P12: Input 1, GPIO, Pull-up, Switch, Link to out 1
```
screen
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/54954537/67a4d10b-8c54-4167-94b8-b8fe576f28be)
working normal

maybe i am doing something wrong

Regards
Alexander

**Comment by ptvoinfo** [comment]
@olekdata Hi, 
Where do you watch incoming data? If it is Z2M, do you use a custom converter? What version of Z2M do you use? Did you try to enable debug logs in Z2M?

**Comment by olekdata** [comment]
Version Zigbee2MQTT : 1.28.0-dev commit: [ddc4345](https://github.com/Koenkk/zigbee2mqtt/commit/ddc4345)

get state with CC2530 on version 1.4 
```
{
    "device_l2": "77",
    "humidity_l2": 60.5,
    "l2": 60.453,
    "linkquality": 149,
    "pressure_l2": 98976,
    "state_l1": "OFF",
    "temperature_l2": 22.4,
    "action": null,
    "l1": null,
    "l10": null,
    "l11": null,
    "l12": null,
    "l13": null,
    "l14": null,
    "l15": null,
    "l16": null,
    "l3": null,
    "l4": null,
    "l5": null,
    "l6": null,
    "l7": null,
    "l8": null,
    "l9": null,
    "state_l10": null,
    "state_l11": null,
    "state_l12": null,
    "state_l13": null,
    "state_l14": null,
    "state_l15": null,
    "state_l16": null,
    "state_l2": null,
    "state_l3": null,
    "state_l4": null,
    "state_l5": null,
    "state_l6": null,
    "state_l7": null,
    "state_l8": null,
    "state_l9": null
}
```

with varsion 1.9 in state not value : humidity_l2, pressure_l2, temperature_l2 etc

**Comment by glcos** [comment]
@olekdata I have the same issue with BMP280, see here https://github.com/ptvoinfo/zigbee-configurable-firmware/issues/222#issuecomment-1678949396

@ptvoinfo in the new firmware release, please keep the same precision, that is 2 digits after the comma, that was in the previous versions. This is very useful in weather monitoring applications.

**Comment by olekdata** [comment]
Problem on Z2M side?
Can i change something set in Z2M?

**Comment by ptvoinfo** [comment]
@olekdata You need the latest version of z2m or a custom converter for your device because the new firmware sends temperature in the other format that the old version of z2m expects.

**Comment by ptvoinfo** [comment]
@glcos, I've double-checked. The firmware sends a temperature with 2 digits after the decimal point.

**Comment by glcos** [comment]
Thanks for your feedback, I will perform other tests as soon as I can.
