### ISSUE TITLE
Model ID won't update

### ISSUE THREAD

**Issue by phalox** [ptvoinfo/zigbee-configurable-firmware#226]
Referring to a closed issue #178

I seem to be experiencing the same issue:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/3983738/e9a3e646-dd6a-4528-a955-576544b89696)

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/3983738/00917de2-e765-4c4a-bc34-d3c0ab5bc69f)

I've deleted the device in Z2M, and restarted Z2M. None of it seems to fix the problem. When I make changes to the firmware (e.g. add an input), they do show up in Z2M.

I've also let it validate that the hex file is correct, and that seems to be the case:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/3983738/4ecb163e-6a7a-46ba-8bb4-7b98c4b03393)

I bumped into one more thing.... When exporting the converter and opening the file, I still see the old name (ptvo.switch).

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/3983738/cffdaf27-91e6-4110-b7d5-608719707fa7)

Could it be that this is part of the issue?

Also, using the custom converter in Z2M, I think it's still not triggered because of the lack of another modelID

_Originally posted by @phalox in https://github.com/ptvoinfo/zigbee-configurable-firmware/issues/178#issuecomment-1703841926_

**Comment by ptvoinfo** [comment]
@phalox Hi,

1. Delete device in Z2M.
2. Stop Z2M.
3. Delete coordinator_backup.json in the "data" folder.
4. Start Z2M.
5. Join the device again.

**Comment by phalox** [comment]
Great, that seems to have solved it! 

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/3983738/b0f12712-8844-496e-819a-6c4eb2778a5c)

What would be your recommended development process? When playing around with different settings, adding & removing sensors etc, this seems a little tedious. I also found it challenging to debug zigbee issues. Often it's a matter of reflashing/repowering, but I'd love some more visibility.

**Comment by ptvoinfo** [comment]
Unfortunately, Z2M is not friendly for DIY :). I use the same procedure while testing/
