### ISSUE TITLE
Trigger functionality is broken on 15/02 release

### ISSUE THREAD

**Issue by zonk-git** [ptvoinfo/zigbee-configurable-firmware#23]
Hello, 
It looks like trigger functionality for GPIO output is broken on 15/02 release of the firmware.
I used this feature with a release I dowloaded previously on oct 31th with success (can not say exactly which version).
Config was : 
```
Board type: CC2530
Device type: Router
Power saving mode (PSM): No
Default reporting interval (s): 300
Output pins:
P13: Output 1, GPIO, External pull-up
```
MQTT message was send with payload `{“trigger”: 200}`
Now trigger still works but **instead of 200ms it releases the trigger at 20 000ms (x100)** 
Changelog says something has been changed about trigger on the Christmas edition, perhaps it is related to this ?
Thanks,
Nick.

**Comment by ptvoinfo** [comment]
Are you using the latest version of  Zigbee2MQTT?

**Comment by zonk-git** [comment]
Nope... I was using 1.16.2.2, and upgraded to 1.17.1-4 and the issue is gone !
Thanks for the advice 👍
