### ISSUE TITLE
Analog values with new UART sensor

### ISSUE THREAD

**Issue by obrain17** [ptvoinfo/zigbee-configurable-firmware#233]
Floating point values are not transmitted correctly over the UART.

1. Send this message to the UART:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/42682043/03d23e5c-64e8-4c8a-b8d9-1b7449482814)

2. Correctly logged in Zigbee2Mqtt:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/42682043/9f9d3323-58ad-46a5-9160-9dafd1aab856)

3. I would expect the value 3DE147AE being sent to the UART:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/42682043/7f781de8-23d0-456c-80f3-ddb0e5876092)

4. Instead AEAEAEAE is sent:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/42682043/84a782ca-5448-473a-8198-9ee876d1abee)

Also for other values always the last byte is repeated 4 times.

The other way it works correctly:
Writing` 21 92 3D E1 47 AE 3B 01` to the terminal will result in:
```
Debug 2023-09-17 20:38:31 Received Zigbee message from 'UART', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":0.10999999940395355}' from endpoint 3 with groupID 0
Info 2023-09-17 20:38:31 MQTT publish: topic 'zigbee2mqtt/UART', payload '{"l3":0.11,"linkquality":76}'
```

**Comment by ptvoinfo** [comment]
@obrain17 I've fixed both bugs related to the UART sensor.

**Comment by obrain17** [comment]
Thank you for the quick reaction.

I just checked both `Analog value` and `Level Control` in both directions and all values are transmitted correctly.

So I am closing the issue now.
