### ISSUE TITLE
CC2652P TX UART does not send serial

### ISSUE THREAD

**Issue by t0p1x** [ptvoinfo/zigbee-configurable-firmware#236]
I configured zigbee CC2652P router mode end device does not send any serial
![config zigbee](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/25056188/cce5061e-86c6-46d8-8636-08621231386f)

For coordinator I use Tasmota
serial log results when connected to an end device like this

15:08:06.310 ZIG: ZbZNPSent 250428DA28DA01
15:08:06.360 ZIG: {"ZbZNPReceived":"650400"}
15:08:06.411 ZIG: {"ZbZNPReceived":"458428DA0028DA14010401FEFF000400001400070006000200000600"}
15:08:06.416 RSL: RESULT = {"ZbState":{"Status":33,"Device":"0xDA28","Endpoint":"0x01","ProfileId":"0x0104","DeviceId":" 0xFFFE","DeviceVersion":0,"InClusters":["0x0000","0x0014","0x0007","0x0006"],"OutClusters":["0x0000","0x0006"]}}

**Comment by ptvoinfo** [comment]
@t0p1x Could you please describe how do you test UART on CC2652? Did you try to swap TX and RX wires?

**Comment by t0p1x** [comment]
data sent from the end device to the coordinator was successful, but not from the coordinator to the end device
for endpoints 1 and 2, the GenMultiStateValue part is input only
![WhatsApp Image 2023-09-25 at 11 58 14](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/25056188/2cac1771-499d-484f-9ae4-fd387a87cda3)

**Comment by t0p1x** [comment]
Thank you for your help
Finally I can send serial data using zigbee2mqtt
In the tasmota program there is no command to send serial data
