### ISSUE TITLE
Two DS18B20, only one working

### ISSUE THREAD

**Issue by Enjoy-Combi** [ptvoinfo/zigbee-configurable-firmware#237]
Hi,

First try with ptvo.
My project consists in 2 DS18B20 and one relay, here after my config:
<img width="589" alt="config" src="https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/11709ce3-6854-40ee-ba5d-c25e11d4cfe9">

Relay works good. Only one temperature is reported. I was thinking first it was due to a faulty sensor. I have unsoldered one of them, the remaining one works. I did the same with the second one (only this one soldered), and the second one works as well. They both works when alone in the circuit. When I have the two ones, only one works.

What I get from the MQTT :
`Debug 2023-09-29 08:51:51Received Zigbee message from 'Ballon eau chaude et température garage', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 3 with groupID 0
Info 2023-09-29 08:51:51MQTT publish: topic 'zigbee2mqtt/Ballon eau chaude et température garage', payload '{"device_l1":"28-93-8C-C7-13-19-01-0D","l1":22.125,"linkquality":105,"state_l3":"OFF","temperature_l1":22.1,"temperature_l2":null}'
Debug 2023-09-29 08:51:52Received Zigbee message from 'Ballon eau chaude et température garage', type 'attributeReport', cluster 'genAnalogInput', data '{"description":"C,28-69-DE-DC-13-19-01-0A","presentValue":22.1875}' from endpoint 1 with groupID 0
Info 2023-09-29 08:51:52MQTT publish: topic 'zigbee2mqtt/Ballon eau chaude et température garage', payload '{"device_l1":"28-69-DE-DC-13-19-01-0A","l1":22.188,"linkquality":105,"state_l3":"OFF","temperature_l1":22.2,"temperature_l2":null}'
Debug 2023-09-29 08:51:52Received Zigbee message from 'Ballon eau chaude et température garage', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2218}' from endpoint 1 with groupID 0
Info 2023-09-29 08:51:52MQTT publish: topic 'zigbee2mqtt/Ballon eau chaude et température garage', payload '{"device_l1":"28-69-DE-DC-13-19-01-0A","l1":22.188,"linkquality":105,"state_l3":"OFF","temperature_l1":22.18,"temperature_l2":null}'
Debug 2023-09-29 08:51:52Received Zigbee message from 'Ballon eau chaude et température garage', type 'attributeReport', cluster 'genAnalogInput', data '{"description":"C,28-93-8C-C7-13-19-01-0D","presentValue":22.125}' from endpoint 1 with groupID 0
Info 2023-09-29 08:51:52MQTT publish: topic 'zigbee2mqtt/Ballon eau chaude et température garage', payload '{"device_l1":"28-93-8C-C7-13-19-01-0D","l1":22.125,"linkquality":105,"state_l3":"OFF","temperature_l1":22.1,"temperature_l2":null}'
Debug 2023-09-29 08:51:52Received Zigbee message from 'Ballon eau chaude et température garage', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2212}' from endpoint 1 with groupID 0
Info 2023-09-29 08:51:52MQTT publish: topic 'zigbee2mqtt/Ballon eau chaude et température garage', payload '{"device_l1":"28-93-8C-C7-13-19-01-0D","l1":22.125,"linkquality":109,"state_l3":"OFF","temperature_l1":22.12,"temperature_l2":null}'`

Any idea what is wrong ?
<img width="343" alt="data" src="https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/e4b8ec8b-c86f-4f9d-8fc3-56e17c6e0c70">

One more question, I don't figure out the logical between input & output.  For me the two ds18b20 behave as an input and the gpio behaves as an output. And they are all selected as output in my config (as per some examples I have seen on the net).

Many thanks for your help !

**Comment by ptvoinfo** [comment]
@Enjoy-Combi 
1. You should specify your sensor ID in the corresponding field.
2. Input/Output role is important for GPIO. It does not affect other sensors.

**Comment by Enjoy-Combi** [comment]
1. Noted, I tried to do it and then no temperature at all. I mean, no field temperature anymore, only the one for the switch. Will try to do it again. I assume there is no order to respect, anyway I will try in both order.
2.Thank you for that information !

**Comment by ptvoinfo** [comment]
1. Try to rejoin the sensor...

**Comment by Enjoy-Combi** [comment]
What I get with this config:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/349e4e9e-7db2-4d33-9076-fbf74913cecb)


I removed the sensor and pair it again:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/d6f6ffd3-e9d7-48e6-909f-319474cb41a9)

**Comment by Enjoy-Combi** [comment]
I changed the order of the temp id:
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/7f44e9a0-3ec3-415b-a507-561c494fb001)

Removed & rejoined the sensor and same issue. I am lost

**Comment by ptvoinfo** [comment]
Do you have the external 4.7k resistor on P15?

**Comment by Enjoy-Combi** [comment]
Yes I have.

Crazy point, I went to the log and I see:
2023-10-02 09:03:59MQTT publish: topic 'zigbee2mqtt/0x00124b000959024a', payload '{"linkquality":72,"state_l3":"OFF","temperature_l1":23.06,"temperature_l2":22.93}'

What is OK.

And the entities are well available:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63100556/19ed5522-a8af-4bd9-9654-5b97867d8da4)

Only surprising that all entities are not available into Zigbee2mqtt.
I fear that I didn't fully follow the tutorial about DS18B20, have to create a sensor to gather all entities.

Then fixed, many thanks for your support
