### ISSUE TITLE
limited functionality PSM

### ISSUE THREAD

**Issue by kuradi** [ptvoinfo/zigbee-configurable-firmware#242]
i got this warning but there are no info which ones have limited functionality. help?
![image_2023-10-21_103143727](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/31483391/e2f71742-2776-443f-a7a7-e75498999d4d)

**Comment by ptvoinfo** [comment]
@kuradi It is a warning about a power amplifier.
