### ISSUE TITLE
Is CC2652R7 supported by CC2652P7 Target?

### ISSUE THREAD

**Issue by vondraussen** [ptvoinfo/zigbee-configurable-firmware#244]
Hi great tool!
I was wondering if CC2652R7 is supported by the CC2652P7 Target?

**Comment by ptvoinfo** [comment]
Sorry, but I didn't try it myself. I think, it should work if you add the "RF level control" output and set the default level to 5dBm.

**Comment by vondraussen** [comment]
Thanks for your fast response. I'm especially interested in the CC2652R7 since it seems to support both zigbee and thread/matter.
