### ISSUE TITLE
Doesn't respond to Read Reporting Configuration Request

### ISSUE THREAD

**Issue by martynwendon** [ptvoinfo/zigbee-configurable-firmware#25]
Can the firmware respond to these with the current reporting configuration?

At the moment they seem to be ignored, even though they are Acked at the APS layer.

![image](https://user-images.githubusercontent.com/1092273/110762865-2f235400-8249-11eb-9fbc-fd22a4863eb6.png)

![image](https://user-images.githubusercontent.com/1092273/110762972-49f5c880-8249-11eb-8dc1-3da5478b8090.png)

**Comment by ptvoinfo** [comment]
The firmware does not support this command.

**Comment by martynwendon** [comment]
Does it not allow configuration of Attribute reporting?

It seems to reply with "success" message when setting:


![image](https://user-images.githubusercontent.com/1092273/110789633-01013c80-8268-11eb-8275-950857ce53ed.png)


![image](https://user-images.githubusercontent.com/1092273/110789002-48d39400-8267-11eb-9cb3-90250130f654.png)

The natural follow up to that is to send a Read Reporting Configuration Request in order to repeat back the configuration and make sure that it matches what was sent.
