### ISSUE TITLE
Auto disconnect from Zigbee network

### ISSUE THREAD

**Issue by MarkStephan89** [ptvoinfo/zigbee-configurable-firmware#250]
Hi, 
 I use a cc2531 and these firmware: 

```
Board type: CC2530 (without external oscillator, like CC2531 dongle or Sonoff BasicZBR3)
Device type: End device without routing
Update firmware's timestamp : 2023-11-14
Enable watchdog timer: Yes
Status LED: P00, Joining or errors
Set default reporting interval (s): 10

Output pins:
P02: Output 1, DS18B20, External pull-up (Sensor ID (optional, hex): )
```

After hours or few days the cc2531 is disconnecting from the zigbee network and is in the pairing mode (led is blinking). 

Any idea?

Many thanks

**Comment by ptvoinfo** [comment]
@MarkStephan89 
Usually, this problem may be caused by other problems in your network. For example, some Tuya devices may frequently rejoin to a network. You can debug this issue by trying to connect the device to a separate test network with a limited number of devices.
