### ISSUE TITLE
E-Byte E72 interview fails with zigbee2mqtt

### ISSUE THREAD

**Issue by u20p17** [ptvoinfo/zigbee-configurable-firmware#253]
Hello,
I have a E-Byte E72 want to flash a ptvo firmware with the following settings:
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63282286/c0a2b372-7bb4-4536-8a06-6c22caf27321)
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63282286/47ddc14b-cca1-454f-bc81-6f7554430b4a)
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63282286/d9703a37-5636-419d-bb54-8e9782868b3f)

I flashed it with openocd via jtag and tried to pair it with zigbee2mqtt. There the sensor gets recognized, but the interview fails, why?

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63282286/89fa225e-c549-4d15-9e0c-6e1918f457e9)

**Comment by u20p17** [comment]
after setting the following specific settings it seems to work (at least when I change the state of the GPIO input it sends a action message- not sure if it does not send periodic messages because it is configures as end device?):
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/63282286/6c95dcf2-54e5-4942-86a2-43d334a7c2b8)

seems that the legacy parameter must be set to false... (default is true)...

**Comment by u20p17** [comment]
@ptvoinfo : any idea why it does not send mqtt messages via zigbee2mqtt in regular intervals as specified in the Expert settings tab of ptvo?

**Comment by ptvoinfo** [comment]
@u20p17 The firmware does not send periodic reports for inputs and UART because the firmware waits for an event from the corresponding pin. For example, if you add a GPIO output, you will receive periodic reports for it.
