### ISSUE TITLE
Reading multiple Attributes from Basic Cluster simultaneously returns corrupted and fragmented data

### ISSUE THREAD

**Issue by martynwendon** [ptvoinfo/zigbee-configurable-firmware#26]
When reading multiple Attributes simultaneously:

![image](https://user-images.githubusercontent.com/1092273/110764370-e1a7e680-824a-11eb-994b-8852e0229ce4.png)

Multiple fragmented packets are received at the APS layer:

![image](https://user-images.githubusercontent.com/1092273/110764513-1025c180-824b-11eb-9fc9-40e1de890959.png)

![image](https://user-images.githubusercontent.com/1092273/110764708-495e3180-824b-11eb-9721-97c41455e6c2.png)

![image](https://user-images.githubusercontent.com/1092273/110764794-61ce4c00-824b-11eb-8c8e-09cc5e0cc66f.png)

![image](https://user-images.githubusercontent.com/1092273/110764863-76124900-824b-11eb-997f-86768f987046.png)

Reading the Attributes individually works OK, and reading slightly less Attributes (i.e. 7 instead of 8) also works OK.

![image](https://user-images.githubusercontent.com/1092273/110765186-d86b4980-824b-11eb-9d10-a5206aee558d.png)

**Comment by ptvoinfo** [comment]
I cannot fix this problem (?) because it relies on the Zstack 1.2 implementation.

**Comment by martynwendon** [comment]
That's OK, I can work around it in the coordinator by read requesting Attributes individually rather than in bulk.

I figured I'd report it as an issue though since it can cause the coordinator (in my case Hubitat / SmartThings) to throw errors as it tries to process those malformed packets.

I'll take a look at the Zstack 1.2 to see if anything stands out, if it's a bug in their implementation I'd have thought it would have surfaced previously as bulk reading of Attributes is pretty common.
