### ISSUE TITLE
no external sensor voltage

### ISSUE THREAD

**Issue by mipoat** [ptvoinfo/zigbee-configurable-firmware#261]
I'm having a hard time getting supply voltage for my DS18B20 sensors when P10 is configured as external sensor power control.

I have a premium license and I'm generating a PSM hex file.
I've hooked up 2 DS18B20 sensors to VCC and can read them out without any problem with the configuration below.
However, if I use P10 as supply voltage for these sensors, I'm not getting any data.
Measuring P10 with an oscilloscope I don't see any signal, only 0V no matter for how long I inspect this pin.
This is true even when nothing is attached to P10 and it is floating without any load attached to it.

my config:
![Settings](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/48950855/01276194-f7a9-4d8a-9b22-4f30f8c3d45c)

![Expert](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/48950855/cbb1a884-2b9d-4f39-ac3c-6b717d7e1a01)

If I generate an end device firmware and set P10 as GPIO output, I can toggle it with the toggle switch in the zigbee2mqtt GUI.
So the pin is working.

Any ideas?

**Comment by mipoat** [comment]
Out of despair I tried the exact same version like here: https://github.com/ptvoinfo/zigbee-configurable-firmware/issues/159

Same configuration options produce 3,3V on P10 with version 2022-10-20 everytime the device wakes up and reads the sensors:
![Settings1 7 3 0](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/48950855/77979275-5f35-4979-bd23-7966fb9c9fc8)


Can you @ptvoinfo please check what is wrong with the latest version?
I'm not sure if it is a good idea to use the old version 2022-10-20, because I see some DS18B20 related fixes in the changelog between this and the most recent version.

**Comment by keynote11** [comment]
I have the same issue with a cc2530.

**Comment by ptvoinfo** [comment]
@keynote11 Did you try the latest version of the firmware?

**Comment by keynote11** [comment]
@ptvoinfo yes try with the latest firmware. This is my config:

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/94765165/da15b122-2b4f-4b39-b3d1-fe17240f6d44)

**Comment by ptvoinfo** [comment]
@keynote11 Could you please try the latest version?

**Comment by keynote11** [comment]
@ptvoinfo if the sensor is sending, i have on p10 3 Volts, is this correct?

**Comment by ptvoinfo** [comment]
@keynote11 yes, correct.
