### ISSUE TITLE
Pulse switch interval less than 1 second?

### ISSUE THREAD

**Issue by Giro-S** [ptvoinfo/zigbee-configurable-firmware#262]
For first a big thank you for these great firmwares/softwares!
My first approach on these devices (CC2530) it was only some days ago and I'm studing on it very much.

When we select as output a "pulse switch" the inteval is only ever 1 second, it would be like to set also a scale of 100ms.
I need a relay that turn on with a push button (in Home assistant) and turn off itself after 300ms.

Is it possible?

Thank you very much

**Comment by ptvoinfo** [comment]
@Giro-S Sorry, but currently, you cannot use shorten intervals.

**Comment by Giro-S** [comment]
Thank you! I hope in the next future.
Best regards
