### ISSUE TITLE
PSM mode: 8 input switches needed

### ISSUE THREAD

**Issue by HelmiBeh** [ptvoinfo/zigbee-configurable-firmware#263]
I need 8 input switches in PSM mode. Can I define one pin for wake up using an OR gate and use 8 different inputs for the switches?

**Comment by ptvoinfo** [comment]
@HelmiBeh Why do you need a separate wake-up button? Any input button wake-ups your device.

Please note, if you really require switches with fixes ON/OFF states (not clicking buttons), then CC2530 allows you to add 4 switches in total (hardware limitation).
