### ISSUE TITLE
Read config from firmware

### ISSUE THREAD

**Issue by iqubik** [ptvoinfo/zigbee-configurable-firmware#264]
Hello dear zigbee master!

I want to flash letv 8 buttons remote controller and find old firmware for that. But it's firmware is very old and eat battery.
I try to read settings from firmware but get program error.
https://github.com/diyruz/freepad/tree/master
https://github.com/diyruz/freepad/releases/download/2.0.7/DIYRuZ_FreePad_LeTV_PM3.hex
Can you might to see to this repo to add support of read this firmware options.

Заранее благодарю.

**Comment by ptvoinfo** [comment]
@iqubik Sorry, but you can only read the settings from a PTVO-based firmware.
