### ISSUE TITLE
HDC2080 sensor does not work

### ISSUE THREAD

**Issue by deaxx** [ptvoinfo/zigbee-configurable-firmware#265]
![hdc2080](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/28512561/d1d8f305-7312-466c-b4e9-27143114bcaf)
![hdc2080_1](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/28512561/70472b22-0883-42b7-b46b-baf07b0c4363)
![hdc2080_2](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/28512561/6127218b-f1ec-42e3-b1cf-1b99153f9ede)
![IMG_20240216_124441](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/28512561/2ed3e968-baf0-4679-8a49-ba4e5bd6d034)

**Comment by deaxx** [comment]
it works on release 2024-03-19.

**Comment by ptvoinfo** [comment]
@deaxx Thank you for testing it!
