### ISSUE TITLE
ws2812 num is always 10, no matter what num i defined in the firmware

### ISSUE THREAD

**Issue by Aubrey-207** [ptvoinfo/zigbee-configurable-firmware#269]
I use cc2530 and 5 led ws2812 led-strip, the question is that no matter what led count i defined , the zigbee2mqtt always recognize 10, and the strip is light 10 leds.
Can you help me solve this.
![Uploading 111.png…]()

**Comment by ptvoinfo** [comment]
Are you using the premium version?
