### ISSUE TITLE
Active Endpoints Response should be in ascending order

### ISSUE THREAD

**Issue by martynwendon** [ptvoinfo/zigbee-configurable-firmware#27]
The response to an active endpoints request should be in ascending order of endpoint id.

At the moment it's not in ascending order.

![image](https://user-images.githubusercontent.com/1092273/110771215-27b47880-8252-11eb-9b30-66d2f05ead15.png)

![image](https://user-images.githubusercontent.com/1092273/110771499-78c46c80-8252-11eb-9c4b-baa073ba07e7.png)

**Comment by ptvoinfo** [comment]
I cannot fix this problem (?) because it relies on the Zstack 1.2 implementation.

**Comment by martynwendon** [comment]
Thanks for the quick reply!

The problem here is that coordinators such as Hubitat and SmartThings (where I am planning on using devices with your firmware) tend to use the first endpoint returned in the list to set the "main" endpoint for a device.  This can make things a little screwy if it's not actually the first endpoint.

The spec does indicate that the list should be in ascending order - https://zigbeealliance.org/wp-content/uploads/2019/11/docs-05-3474-21-0csg-zigbee-specification.pdf

Perhaps the Zstack returns them in whatever order you are storing / adding them when the are configured in the configuration software?

**Comment by ptvoinfo** [comment]
I've implemented a workaround in the latest version related to this problem.
