### ISSUE TITLE
Filter input GPIO

### ISSUE THREAD

**Issue by Arthuret** [ptvoinfo/zigbee-configurable-firmware#278]
Hello,
I use your firmware to read 230V wall, standard buttons, through a reduction and limiting circuit and an opto-coupler. The AC side has two leds, thus the DC side see a 100Hz (AC is 50Hz) signal. It works fine most of the time, and always on the target button, but sometimes, a parasite passes through (this is AC afterall), and the controller see a pulse on all buttons.

TLDR : Is there a way to add a filter to GPIO inputs ? As in take a sample every 1-3 ms, and register the input changed only after x samples are equals ?

**Comment by ptvoinfo** [comment]
Sorry, but firmware does not have such logic.
