### ISSUE TITLE
Something wrong with ADC in PSM mode

### ISSUE THREAD

**Issue by axelhorn** [ptvoinfo/zigbee-configurable-firmware#282]
The problem with the controller forcing the ADC input (any used one) to 0V immediately after the first work-sleep cycle remains unsolved until the current firmware version.
It occurs on both the CC2652P and CC2652RB, which I am currently creating a new device on.

_Originally posted by @axelhorn in https://github.com/ptvoinfo/zigbee-configurable-firmware/issues/216#issuecomment-2143739515_
            
![obraz](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/73194444/a0cfc7b4-f6b5-4e3f-9135-884c7d30f95e)

**Comment by ptvoinfo** [comment]
@axelhorn Sorry about the delay with my answer. Summer time :). I've checked your configuration with CC2652R1 and cannot repeat this problem. Did you try this setup with constant voltage on P23 too? Did you try it without Output 5?
