### ISSUE TITLE
Button status (clicked/not clicked) not reported to home assistant

### ISSUE THREAD

**Issue by islamessam** [ptvoinfo/zigbee-configurable-firmware#289]
Hello,
Thanks for the great effort. I tried to create a light switch with 3 buttons and 3 relays mapped to each others.
The device is detected on ZHA and working properly (when button is clicked the relays toggle)

However in Home assistant, Button status is not reported (always showing as not clicked even when clicked).

Is there any way to solve this?

**Comment by ptvoinfo** [comment]
The firmware reports clicks for unlinked buttons only.
