### ISSUE TITLE
RSSI is not reported on ZHA

### ISSUE THREAD

**Issue by islamessam** [ptvoinfo/zigbee-configurable-firmware#290]
Hello,
Any way to report  the RSSI on ZHA ?

**Comment by ptvoinfo** [comment]
@islamessam As I know, it is present but hidden by default in ZHA.

**Comment by islamessam** [comment]
Thanks alot for your reply. Yes it is hidden but when I enable it it always show.Only the LQI is reporting from 0 to 254On 5 Jul 2024 6:25 am, ptvo ***@***.***> wrote:
@islamessam As I know, it is present but hidden by default in ZHA.
