### ISSUE TITLE
Value glitch double i2c 

### ISSUE THREAD

**Issue by TomasWeij** [ptvoinfo/zigbee-configurable-firmware#296]
Hi,

I've added two HX711 sensors to my firmware config. See screenshot below. My report interval is every 2s. One input shows the value and updates it every 2s as expected. The other value jumps between 0 and the actual value. The firmware has been flashed on the RF-Star CC2652P2. 

I suspect it has something to do with the shared I2C clock. If I physically unplug the first HX711 then the second value doesnt jump to 0 anymore.

![ptvo_config](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/29373465/ce486cb7-6c0f-4c71-9ce4-3394a91e98b3)

**Comment by TomasWeij** [comment]
I'm willing to compensate you, please contact me.

**Comment by ptvoinfo** [comment]
@TomasWeij I've tested this configuration. Please try to shift P21 and P13 down (to Output 4 & Output 5). Leave one unused Output 3 between sensors in the configuration. After this, you'll need to re-create a custom converter (if used).
