### ISSUE TITLE
PZEM-004 V3 + CC2530

### ISSUE THREAD

**Issue by bdariusb** [ptvoinfo/zigbee-configurable-firmware#299]
I have an issue with reported power results. I used the latest firmware, z2m 1.39.0 and generated z2m custom converter. If you look in the attached picture, the voltage and current, the calculated power is much higher than expected (~10x higher?)
![z2m](https://github.com/user-attachments/assets/5f4a3fc7-7206-4ff8-918a-4c4bab5c2a1a)
![settings](https://github.com/user-attachments/assets/88de520e-cc7f-4105-94d6-1df26cf959d6)

**Comment by ptvoinfo** [comment]
@bdariusb Could you please download and try the latest version? You should re-flash the firmware only.

**Comment by ptvoinfo** [comment]
@bdariusb I've removed this parameter from reporting because it is a constant 99.99% of time.

**Comment by bdariusb** [comment]
> @bdariusb I've removed this parameter from reporting because it is a constant 99.99% of time.

Understandable, thanks
