### ISSUE TITLE
Node Red switch on off gives "Failed to parse JSON string" 

### ISSUE THREAD

**Issue by shahglobal** [ptvoinfo/zigbee-configurable-firmware#3]
Hi,
I toggle switch through the node-red web page, it works but the MQTT "in" node that I use to update the switch status gives me "Failed to parse JSON string" error. Not sure if its the node-red issue or the string that comes out of the switch. Just wondering where to look any pointer would be appreciated:
Thank you so much
Shah

Here is my nodered setup:
zigbee2mqtt/0x00124b001ef965ab/# --->payload.state_l1--->on/off switch--->Toggle switch.0x00124b001ef965ab_switch_l1
![image](https://user-images.githubusercontent.com/49333238/94349127-8a90bb00-fff6-11ea-8109-5f77ba22608a.png)

**Comment by ptvoinfo** [comment]
Hello Shah.

I think this problem is related to NodeRED. You should enable debug log-files in Z2M and check the real MQTT payload there.

**Comment by shahglobal** [comment]
Awesome, Thank you, sir.
