### ISSUE TITLE
Multiple DS1820B reported on l1 instead of l1, l2, l3 and l4

### ISSUE THREAD

**Issue by fibrinogen** [ptvoinfo/zigbee-configurable-firmware#300]
Hi, thank you for your work!

I have a cc2530 and attached four DS1820b to PIN 15.

Configuration in PTVO is as follows:
![image](https://github.com/user-attachments/assets/5f8a2b2f-8812-4e4e-9ba3-bf165e957f73)

In zigbee2mqtt all four temperatur readings are reported on l1 instead as expected on l1, l2, l3 and l4.

![image](https://github.com/user-attachments/assets/5f9b1ccf-cd24-43ef-b8cd-629b056b8871)

I can still read the temperatur values in the different messages and ditinguish by the sensor ID, that is delivered inside the mqtt message.

**Comment by ptvoinfo** [comment]
You should configure the Sensor ID and select the corresponding mode for each output. Otherwise, the firmware does not know where it should output a value.
