### ISSUE TITLE
Better explanation needed for the use of input 1 for a pairing button

### ISSUE THREAD

**Issue by rmtucker** [ptvoinfo/zigbee-configurable-firmware#304]
Still waiting on my CC2530 and programmer arriving but having trouble with firmware config:
I wish to have 2 DS18B20 sensors,1 on output 1,and 1 on output 2 as pic
![Screenshot from 2024-08-29 12-44-52](https://github.com/user-attachments/assets/e84c074e-99c1-4530-9917-902c62cdb5a1)
But then if i try to add input 1 external wake up it gives the following error
![Screenshot from 2024-08-29 12-44-30](https://github.com/user-attachments/assets/86344072-6477-453c-9417-16fd6522f732)
I just want to add an external button for pairing (hold for 10 secs)
Or should it just be set as GPIO and switch?

**Comment by ptvoinfo** [comment]
@rmtucker You cannot combine DS18B20 and "External wakeup" on the same line #1 (endpoint #1). It is the internal limitation.
You can shift DS18B20 to Output 2 & 3.

**Comment by rmtucker** [comment]
I understand thank you
But is external wakeup the correct choice for a pairing button,or should it be just as switch on gpio?

**Comment by ptvoinfo** [comment]
The External wakeup button on Input 1 can also work as a paring button.
