### ISSUE TITLE
Icon is not displayed in Z2M 

### ISSUE THREAD

**Issue by Maschler** [ptvoinfo/zigbee-configurable-firmware#305]
Hi!
First of all, congratulations on the great software and thanks for sharing!!! I was able to implement what I wanted to do with it and I'm really excited.

However, I noticed two things. To keep a better overview, I have opened two issues.
(Zigbee2MQTT version: 1.39.1, PTVO version: 2.5)

1. I would like to display an icon in Z2M. I have downloaded the desired .png (see **Fig 1**) and loaded it under “Expert” (see **Fig 2**).

2. Then I placed the generated **Test_26.js** for Z2M in the DATA folder and coupled the flashed CC2530 (which worked great)
3. Unfortunately no icon is displayed in Z2M (see **Fig 3**).

Was my procedure wrong? Is the .png too big (are there any limits)?

**Test_26.js**
[Test_26js.txt](https://github.com/user-attachments/files/16921538/Test_26js.txt)
**Fig 1**
![Fig 1](https://github.com/user-attachments/assets/e4df21c5-a80b-4c3a-b2b2-ffb7a46ff56a)
**Fig 2**
![Fig 2](https://github.com/user-attachments/assets/45bf843f-5420-4ab6-b21c-421e529d0e27)
**Fig 3**
![Fig3](https://github.com/user-attachments/assets/0c65b83e-3232-4d1b-a194-378cc042b5a9)

**Comment by ptvoinfo** [comment]
@Maschler Did you add your converter to the Z2M configuration? Did you try to restart Z2M afte it?

**Comment by Maschler** [comment]
Thank you for your answer.

I used the Costom Converter like in Fig 2 shown. Afterwards I then transferred the generated Test_26.js to the Z2M data folder and restarted Z2M. After this I paired the cc2530.

Is the size of the picture to large? (Dimensions 3000x1875 pixels)

**Comment by ptvoinfo** [comment]
It is not enough. You should add your converter to the Z2M configuration.
configuration.yaml -> external_converters:

**Comment by Maschler** [comment]
Ohhh. This solved both issues. Once again, the problem was sitting in front of the screen... Thank you very much!
