### ISSUE TITLE
z2m loads external converter but doesnt seem to apply it?

### ISSUE THREAD

**Issue by gingemonster** [ptvoinfo/zigbee-configurable-firmware#311]
I have specified the custom convert .js file (created in the firmware app) in the z2m settings and when I reload z2m I get:

[2024-12-02 13:44:39] info: 	z2m: Loaded external converter 'GM.KeyHook1.js'

the converter js has this line to match by model:

const ptvo_switch = (zigbeeHerdsmanConverters.findByModel)?zigbeeHerdsmanConverters.findByModel('ptvo.switch'):zigbeeHerdsmanConverters.findByDevice({modelID: 'ptvo.switch'});

and z2m shows that as my devices model:

![image](https://github.com/user-attachments/assets/e7e33d26-fdd6-45bf-b80c-b0c06c1ccf60)

Yet the custom description, manufacturer etc I set in the js is not getting applied and Im not sure anything is actually being applied (these are just the easy things to see):

const device = {
    zigbeeModel: ['GM.KeyHook1'],
    model: 'GM.KeyHook1',
    vendor: 'Gingemonster',
    description: 'TEST [Configurable firmware](https://ptvo.info/zigbee-configurable-firmware-features/)',
    
  Any ideas?

**Comment by gingemonster** [comment]
Ok found the issue, although I have these settings in the advanced of the firmware:

![image](https://github.com/user-attachments/assets/2ec76614-a255-4232-9510-4b3a09b17cd3)

My device is still reporting itself as a ptvo.switch so the converter js exported from the firmware tool does not match the device. Manually reverting it back to the defaults made the converter load correctly.

Now things are working as expected except there are a lot of additional controls, settings and sensors exposed to home assistant that Im sure are correct I just dont really understand what they represent:

![image](https://github.com/user-attachments/assets/ada7e27d-b2c4-4b70-b844-120a716510f6)

A future article on the documentation expanding a bit more on what these are and how to hide them if not needed would be much appreciated

Thanjs

**Comment by alainvdu69** [comment]
Hi !
I've big trouble with external converter too.
At this time, i'm not using it ... 
But, perhaps it's the same trouble with the powersource issue you have.
So, try to delete, restart z2m, and repair with the fresh firmware with the converter enabled.

I will make further experiments to find the right solution.

**Comment by gingemonster** [comment]
yes was z2m caching previous entry when on batteries and not the latest flashed firmware
