### ISSUE TITLE
z2m seems battery device as mains powered

### ISSUE THREAD

**Issue by gingemonster** [ptvoinfo/zigbee-configurable-firmware#312]
using the PSM device type in z2m I can see the battery being reported but the device is show as being mains powered:

![image](https://github.com/user-attachments/assets/32e7b6db-c3e1-473b-b493-ea2f4844ad11)

Therefore z2m marks it as unavailable too soon as it doesnt think its battery powered. I cant see how to change this in the external converter so presumably it needs to be in the firmware?

**Comment by alainvdu69** [comment]
hi !
if you have already used and paired the device with another powersource, this mistake can happen : it's happen to me !
delete the device.
wait a while.
reboot z2m
and repair the device only in the PSM mode
