### ISSUE TITLE
messages repeated six times

### ISSUE THREAD

**Issue by alainvdu69** [ptvoinfo/zigbee-configurable-firmware#313]
Hi !

I've noticed that all my ptvo devices (3 with PZEM-004T on AC/DC power) (3 in PSM mode on battery) repeat the zigbee message 6 six times.
I've discovered this with MQTT Explorer.
For exemple, on a PSM device, with à periodic report of 30 minutes :
we can see a flow of 6 messages with a very short timelaps, and 30 minutes before, the flow of the past 6 messages.

![image](https://github.com/user-attachments/assets/f78bba92-8bc2-40d1-8203-049dae56c96d)
![image](https://github.com/user-attachments/assets/79b6dbdb-b395-4768-990f-afc591360685)
![image](https://github.com/user-attachments/assets/eb7d94d6-6cd0-4db8-ad5e-e2c1765f332b)
![image](https://github.com/user-attachments/assets/c721a6ae-2502-488e-b8eb-7b7d35ab4a28)

It's very strange.
my other devices (SONOFF, NOUS, ORVIBO, ...) don't have the repetition of the message.

the firmware for the PSM devices was build with the PTVO from july 2024 version, and the others devices have a more older version of PTVO (year 2022.)

**Comment by ptvoinfo** [comment]
The device sends one Zigbee data packet per a value. So, you see these separate messages in Z2M and MQTT. Set the "debounce" parameter to "1" in the device settings in Z2M. Then Z2M will group these messages.

**Comment by alainvdu69** [comment]
yes, well done.
solved.
thanks.

**Comment by alainvdu69** [comment]
but, there were a drawback ...
sometimes, the device send usefull messages in a very short laptime, and the debounce to 1 drop them.
so, i have to add the relevant id of values to the 'ignore anti-rebond' :
![image](https://github.com/user-attachments/assets/9ad62c2a-3d3d-4e31-aae4-7d0acf90f5c4)
