### ISSUE TITLE
Feature request: slower PWM

### ISSUE THREAD

**Issue by alitaker** [ptvoinfo/zigbee-configurable-firmware#32]
Hi, thank you for this great firmware.
I'd like to bllink a load (i.e. a LED) at 0.5Hz, 1Hz or 2Hz. Could you please add this feature to the PWM options? 

Thank you... and I owe you a cofee!

**Comment by ptvoinfo** [comment]
Hi,
Thank you for a coffee :)!

Sorry, but PWM cannot work at this frequency. 

I think you can use a "Pulse generator" option for your task.

**Comment by alitaker** [comment]
Hi, the pulse generator could do, but I do not see a way to stop it counting. Would it be possible to have an on/off cluster for that?

Thank you

**Comment by ptvoinfo** [comment]
Added in the latest version. But the minimum frequency is 4 Hz.

**Comment by alitaker** [comment]
Ok, so it's still a PWM configuration. There is no way to start/stop the pulse generator from an output cluster, right?
Thank you.

**Comment by ptvoinfo** [comment]
Any PWM endpoint also supports the ON/OFF commands.
