### ISSUE TITLE
Feature request: thermocouple sensor

### ISSUE THREAD

**Issue by pilotak** [ptvoinfo/zigbee-configurable-firmware#33]
It would be perfect if MAX31855 or MAX6675 could be added, so i don't have to use co-processor for reading the temperature

**Comment by ptvoinfo** [comment]
Why is it better than other temperature sensors like HDC1080, DS18B20, etc?

**Comment by pilotak** [comment]
i need to measuse high temperature around 150°C

**Comment by pilotak** [comment]
@ptvoinfo it's a pity that this is not going to be supported

**Comment by ptvoinfo** [comment]
@pilotak I've added the MAX31855 sensor some time ago:
https://ptvo.info/zigbee-configurable-firmware-features/external-sensors/max31855/
But only for CC2652 because CC2530 do not have enough memory for this feature.

**Comment by pilotak** [comment]
oh, perfect, thanks a lot
