### ISSUE TITLE
Devices offline after two days offline

### ISSUE THREAD

**Issue by Diddlik** [ptvoinfo/zigbee-configurable-firmware#35]
I have two devices that worked fine after flashing. The day before yesterday I had a short circuit in the line and the fuse went out. 
The devices were offline for two days, and today when the line was repaired, they are no longer on the network. I had to flash them again and repair them. Is it ok that after the long break the devices should be paired again?

**Comment by ptvoinfo** [comment]
Is it a router, end device, PSM, or 16-channel device?

**Comment by Diddlik** [comment]
It is a router. Only used for UART
![grafik](https://user-images.githubusercontent.com/6010713/117409222-3e551400-af11-11eb-9a16-242d79dd439e.png)

**Comment by ptvoinfo** [comment]
Can a power on/off cycle reset this device theoretically?

**Comment by Diddlik** [comment]
possibly yes, because 3-fold on/off activates the mating.
I have tried the fuse several times, so I would say theoretically yes. I have now flashed new ones, I will observe it.

**Comment by ptvoinfo** [comment]
@Diddlik Hi! Did you have a chance to test this problem?

**Comment by Diddlik** [comment]
I have flashed and repaired it. Yesterday I took both devices offline, wait another 2 days, then we'll see ;)

**Comment by Diddlik** [comment]
I switched on the two devices today and both are also online in the zigbee network. It seems to be a problem with short-circuiting.
