### ISSUE TITLE
Bug in PWM output?

### ISSUE THREAD

**Issue by copystring** [ptvoinfo/zigbee-configurable-firmware#36]
Hey,

i'm using a ZigUp with PWM output on P13 with odd results.
Up to a value of 138 is more or less fine. Measuring about 60% duty cycle with my multimeter. It should be 54 but not big deal.
However setting it to 139 the results in roughly 75% duty cycle.
170 goes to 97%
Is my multimeter wrong or a bug in the firmware? I have no further way to test this with my equipment.

**Comment by ptvoinfo** [comment]
Hi,
Sorry, but I don't use the ZigUp firmware. I don't know how to help.

**Comment by copystring** [comment]
I'm not using zigup firmware. Just the zigup hardware with your firmware :)

**Comment by ptvoinfo** [comment]
What PWM frequency do you use? Can this hardware work at that frequency?

**Comment by copystring** [comment]
I'm using 1KHz measuring with UNI-T UT139C. Checked the manual. It should work at that frequency.
Do you think changing the frequency could help?

![image](https://user-images.githubusercontent.com/1298861/117609002-76ea2d00-b15f-11eb-856f-7e92f6e312b2.png)

**Comment by copystring** [comment]
Changed the firmware from 1KHz to 8 KHz.
Then it works just fine.

**Comment by ptvoinfo** [comment]
I mean that ZigUp hardware can be designed for a specific frequency only. It is great that you found the correct value :).

**Comment by copystring** [comment]
Oh. Ok yeah maybe. Thank you!
Love your firmware :)
