### ISSUE TITLE
Можно ли добавить режим термостата с гестерезисом? 

### ISSUE THREAD

**Issue by directman66** [ptvoinfo/zigbee-configurable-firmware#4]
Такой режим бы отлично подошел для реле 4 или 8 канального реле от @Jager_f для управления климатом.

**Comment by ptvoinfo** [comment]
Unfortunately, it is more applicable to a dedicated device. It can be implemented using a higher-level home automation system.
-
К сожалению, это больше подходит для отдельного специализированного устройства. Это также может быть реализовано в системе умного дома.
