### ISSUE TITLE
Feature request: HC-SR04 Ultrasonic sensor

### ISSUE THREAD

**Issue by Mr-Groch** [ptvoinfo/zigbee-configurable-firmware#42]
Could you please add support for ultrasonnic sensor like HC-SR04? 

[Datasheet](https://www.electroschematics.com/wp-content/uploads/2013/07/HC-SR04-datasheet-version-2.pdf)

[ESPHome implementation](https://github.com/esphome/esphome/tree/dev/esphome/components/ultrasonic)

**Comment by ptvoinfo** [comment]
Added in the latest version.
