### ISSUE TITLE
Bug in config tool

### ISSUE THREAD

**Issue by copystring** [ptvoinfo/zigbee-configurable-firmware#43]
This made me insane a few times figuring out why the switch is not working.
Output is read wrong when reading the firmware file.
It's a bug right?

![ptvo bug](https://user-images.githubusercontent.com/1298861/123043549-bc557780-d3f8-11eb-86e9-736057d5b867.gif)

In the .txt file is it saved correctly:

![image](https://user-images.githubusercontent.com/1298861/123043782-19512d80-d3f9-11eb-82b8-d2e225c05973.png)

**Comment by ptvoinfo** [comment]
@copystring Thank you! Fixed in the latest version on the latest version
https://ptvo.info/download/cc2530_io_1.2.2a.44539_firmware.zip?q=1624539384
