### ISSUE TITLE
BME280 capable?

### ISSUE THREAD

**Issue by JonRobert** [ptvoinfo/zigbee-configurable-firmware#5]
Don't know if this is a documentation error I'm missing something.   The feature list shows the capability to use the Bosch BMP280 and BME280.
In the program I only see BMP280 and NO BME280.
Thanks
John

BTW I've not actually used the software yet (hence the BME280 Question) however it promises to be an awesome program.

**Comment by ptvoinfo** [comment]
Hi,

The firmware supports BME280. BMP280 and BME280 are similar.

**Comment by JonRobert** [comment]
Thank you :)

Does your firmware work with Zigbee HA?  I.e. can I connect to Smartthings?   If so can you help me find the details of how the cc2530 will "talk" to the Smartthings Hub?

BR
John

**Comment by ptvoinfo** [comment]
The firmware supports the Zigbee Home Automation standard. But I don't have info about compatibility with the Smartthings Hub.
