### ISSUE TITLE
PWM output Status 'FAILURE'

### ISSUE THREAD

**Issue by copystring** [ptvoinfo/zigbee-configurable-firmware#53]
Hey,

not sure if this a bug or not possible with LAUNCHXL-CC26XC2R1.
I've setup the firmware like this: 
![image](https://user-images.githubusercontent.com/1298861/132997477-9ef6f5c6-bfb5-4e50-a915-393d7edc7708.png)
The sensor on Input3 works fine. LED on P06 works also just fine.

I also need a PWM output. Tried hardware and software PWM with different frequencies and different pins (P25,P23,P00,P12)
When setting a PWM value z2m responds like this:
![image](https://user-images.githubusercontent.com/1298861/132997430-44bb2ea4-ad05-46e1-ac20-919bb1c6a660.png)

However turning the PWM off/on (![image](https://user-images.githubusercontent.com/1298861/132997531-fbc4cde9-55ff-4489-99db-03b3eb77d523.png)) works just fine.
![image](https://user-images.githubusercontent.com/1298861/132997596-5d3b9a2a-4e61-4234-b7eb-d30a65f67158.png)

Confirmed on/off with my multimeter.

Can you help me?

**Comment by ptvoinfo** [comment]
Hi @copystring,

Could you please try the commands described on:
https://ptvo.info/zigbee-configurable-firmware-features/pwm/
?

**Comment by copystring** [comment]
Sure, I tried `zigbee2mqtt/0x00124b001ca15d81/l1/set/brightness 150` and `zigbee2mqtt/0x00124b001ca15d81/set/l1 {"brightness": 150}` but there is no response on the mqtt broker. Multimeter confirmed no change.
After a while the device reports with brightness 255 on l1.

**Comment by ptvoinfo** [comment]
Probably, the device is not fully paired the first time.

**Comment by copystring** [comment]
Thank you!
