### ISSUE TITLE
initial state of GPIO and PWM outputs seems to be HIGH

### ISSUE THREAD

**Issue by hosentraeger** [ptvoinfo/zigbee-configurable-firmware#58]
Hi,

it seems that the default/initial state of GPIO or PWM outputs after powering up the module is HIGH. This requires an appropriate hardware design, for example LEDs connected to VCC or P-FET drivers.

It would be great if the initial state would be configurable!

**Comment by ptvoinfo** [comment]
Fixed in the latest version. Could you please check?

**Comment by hosentraeger** [comment]
sorry, but negative. Same result as before.

I tested with 
- external pull up, no restore last state
- external pull down, no restore last state
- pull down, no restore last state
- external pull up, restore last state
It's always the same, GPIO outputs are LOW, PWM outputs are HIGH.
After sending state OFF resp. brightness 0 to the board, the state will be correctly restored after reboot (if configured).

I wonder if this is not a bug but a feature. What is the desired start-up-behaviour if one doesn't tick "restore last state" on PWM outputs? I did compare PWM outputs with GPIO outputs, where the initial state is LOW. But if one wants to build a light, it would be wise to start it up with full power on.

**Comment by ptvoinfo** [comment]
It seems I didn't understand your description the first time. Yes, it is standard behavior. The firmware initializes PWM output with the maximum level, leading to the HIGH signal on the output.

**Comment by hosentraeger** [comment]
Ok, this is now clear.
I still think it would be a useful feature if you could set the initial state of your outputs, image you have a buzzer that is ON after every firmware update. 
Anyway there is still the option "remember state" so it will really be only a firmware update that would trigger a problem, so I consider it a low priority request.
