### ISSUE TITLE
Add support for temp/humidity sensor SHT40

### ISSUE THREAD

**Issue by MiloshCZ** [ptvoinfo/zigbee-configurable-firmware#60]
Hi,
is it possible to add support for SHT40?

https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT4x_Datasheet.pdf

Thank you

**Comment by tibouh** [comment]
Hi,
Is there a reason why this sensor is not available on CC253x (as of firmware 2024-03-18)?
Can't it be added?
Thanks

**Comment by ptvoinfo** [comment]
@tibouh there is no free space for new features.

**Comment by tibouh** [comment]
I currently have a CC2530+CC2591 module.
I use it for a weather station: 5 ports Pxy are used.
What would you recommend instead?
