### ISSUE TITLE
Add new Board Type for DL-22 (CC2530 + CC2591)

### ISSUE THREAD

**Issue by BoBeRzE** [ptvoinfo/zigbee-configurable-firmware#62]
Hi ptvoinfo

i just found your great configurator and still have a DL-22 in my handicraft box but the wiring is a bit different.

[Info from a old issue](https://github.com/Koenkk/zigbee2mqtt/issues/1362)

Wiring DL-22

P1_4 - PAEN
P1_5 - EN
P0_7 - HGM

I dont know if any other infos are required but in the past you already created a firmware for this device. It is possible to support this device in your configurator?

Keep up the awesome work!

Thank your very much

**Comment by AndrewLinden** [comment]
Support for DL-22 would be nice!
