### ISSUE TITLE
Switching OFF PWM doesnt remember PWM Value

### ISSUE THREAD

**Issue by ranido-code** [ptvoinfo/zigbee-configurable-firmware#72]
Hi, 
Im using the following configuration in my project:

Board type: CC2530 + RFX2401 (config control pins!!!)
Device type: End device without routing
 Transmit enable (TXEN): P11Receive enable (RXEN): P10
Update firmware's timestamp : 2021-11-16
Set default reporting interval (s): 20

Output pins:
P16: Output 1, PWM (Hardware, 128 kHz), Pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level), Remember state
P17: Output 2, PWM (Hardware, 128 kHz), Pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level), Remember state

Input pins:
P06: Input 1, GPIO, Pull-up, Switch, Link to out 1
P07: Input 2, GPIO, Pull-up, Switch, Link to out 2

With this configuration Im able to write different PWM values from iobroker.zigbee to the cc2530.  Im also  able to switch on and off the PWM through iobroker.zigbee. But everytime I change the status from off to on the PWM starts with the value 255 regardless of the value before. 

Switching off/on the PWM with a hardware switch I get the same result. 

In your documentation you write:

If the “switch” option for input is “on,” the switch changes the output state to on or off. The firmware can remember the PWM level before switching off and restore it after switching on. You can set the exact PWM level from a bounded control or a coordinator.

What is going wrong here ... may be my configuration?
Please, can you help me?

**Comment by ptvoinfo** [comment]
Fixed in the latest version. Please, check.
