### ISSUE TITLE
Question/Feature Request: Setting output power for CC2652P/CC1352P2 router configuration

### ISSUE THREAD

**Issue by irakhlin** [ptvoinfo/zigbee-configurable-firmware#75]
My understanding is the default provided configuration from TI for a CC2652P/CC1352P2 router sets the output power at 5dBm, however the chip supports output power of 20dBm. I am hoping to configure a router firmware for a device like this: https://www.tubeszb.com/product/cc_router/4?cp=true&sa=false&sbp=false&q=false&category_id=3

but with increase output power. Does the provided preset firmware example 'cc2652p_TI_LaunchPad_Router.ini' have the power increased? If not would this be possible to add as a configuration feature. As the set 5dBM the CC2652P is proving to have pretty weak range.

**Comment by ptvoinfo** [comment]
The firmware always sets 20dBM for CC2652P.
