### ISSUE TITLE
Add support for E72-2G4M20S1E (CC2652P)

### ISSUE THREAD

**Issue by hdavidka** [ptvoinfo/zigbee-configurable-firmware#76]
Hi!

Can you provide PA TX/RX for GPIO selection for CC2652P board type?
For the module in the title it is the following:
![image](https://user-images.githubusercontent.com/24659934/143281649-6b0cdfe2-9c79-4598-b7ef-2147b2c436b3.png)

**Comment by ptvoinfo** [comment]
PA is built-in to the chip. It is not necessary to configure pins. They are always the same.
