### ISSUE TITLE
Add support for PZEM-017 V1

### ISSUE THREAD

**Issue by ranido-code** [ptvoinfo/zigbee-configurable-firmware#78]
Hi,
in my project I want to meter DC voltage in the range 0 - 15 Volts and DC current in the range of 0 - 100A.
I saw in your configuration the firmware is able to handle a PZEM-004 for AC voltage. So I tried this parameter for a PZEM-017
Version 1,  which is for DC voltage. But it doesnt work.

The reason is, the firmware asks the PZEM device to send the values of 10 registers starting with register 0. Thats correct and may work for a PZEM-004 but not for a PZEM-017. The device only has 8 registers starting at register 0.

See the following log from a PZEM-017:

Sent: 01 04 00 00 00 08 F1 CC                                                                        //ask the PZEM-017 to send 8 registers 
Received: 01 04 10 04 95 00 00 00 00 00 00 00 02 00 00 00 00 00 00 21 40 //the PZEM-017 sends the contents of 8 registers
Sent: 01 04 00 00 00 09 30 0C                                                                        //ask the PZEM-017 to send 9 registers 
Received: 01 84 02 C2 C1                                                                               //the PZEM-017 sends an error
Sent: 01 04 00 00 00 0A 70 0D                                                                        //ask the PZEM-017 to send 10 registers 
Received: 01 84 02 C2 C1                                                                              // the PZEM-017 sends an error too

Is it possible for you, to add the PZEM-017 in your configurable firmware.

Thank you very much for your support.

**Comment by khaidakin** [comment]
Everything works great, including resetting the counter.
