### ISSUE TITLE
CC2652P uptime is always zero

### ISSUE THREAD

**Issue by glcos** [ptvoinfo/zigbee-configurable-firmware#79]
I have this configuration

<img width="587" alt="ptvo" src="https://user-images.githubusercontent.com/22558340/145838050-ac357450-e641-4645-bd6d-5b6812a809dd.PNG">
Everything works fine, apart from the uptime value coming on endpoint 1 that is always 0.0

`Attribute report received: present_value=0.0`

The value does not increase.
Am I doing something wrong ?

**Comment by irakhlin** [comment]
Just to chime in, I am also seeing this behavior with multiple CC2652P  devices.

**Comment by ptvoinfo** [comment]
Could you please try the latest version? I've fixed this problem.

**Comment by irakhlin** [comment]
> Could you please try the latest version? I've fixed this problem.



> .

@ptvoinfo Justm tested it, it seems to be working but I just want to verify, should the counter only update on device report intervals? For example, I configured a device with a virtual GPIO switch that controls an  LED on the board along with the timer. Any time I flip the switch on/off LQI updates but the uptime timer does not, that only updates per the set device report interval. If this is the intended functionality then I can verify it is working.

**Comment by ptvoinfo** [comment]
It is a real-time clock. It increases every second after the system boot.
