### ISSUE TITLE
Configurator doesn't read back "SBL" setting from firmware

### ISSUE THREAD

**Issue by hosentraeger** [ptvoinfo/zigbee-configurable-firmware#85]
File / Read settings from firmware does not check the box "Serial Bootloader(SBL)/Enable SBL" on tab "Expert".
Neither does "File / Read settings from a file" or exiting and restarting the Configurator.
"Save settings to file" does write the config ([Expert.SBL]/Pin=P15) entry though.

**Comment by ptvoinfo** [comment]
Hi,

I've fixed this problem in the latest version 1.6.0.1. Please try it.

**Comment by hosentraeger** [comment]
Hi,
partially working with 1.6.0.1 (Firmware 2021-12-30), the configurator remembers the last set values for "Enable SBL" and "SBL mode activation pin".

Still having trouble with reading back from firmware.

With configurator 1.6.0.1/Firmware 2021-12-30:
Start Configurator
File / Reset to defaults
change "Board Type" to CC2652xxx
-> "Enable SBL" goes on, "SBL mode activation pin" goes to P15
change "SBL mode activation pin" to P13
"Save" firmware to test-sbl-p13.hex
File/reset to defaults
change "Board Type" to CC2652xxx
-> "Enable SBL" goes on, "SBL mode activation pin" goes to P15
change "SBL mode activation pin" to P15
change "Enable SBL" to off
File / read settings from firmware / test-sbl-p13.hex

-> "Enable SBL" is still off, "SBL mode activation pin" is still P15

I could imagine it is nearly impossible to get these values out of the firmware. 

What about a warning dialog box at "Save" that says "no SBL pin given, you won't be able to serial bootload / save anyway / cancel / never mind" resp. "Serial Bootloader will listen on P15 / ok / cancel / never mind"?

**Comment by ptvoinfo** [comment]
Fixed in the latest version.
