### ISSUE TITLE
Configurator: "Status LED" does not allow for some pins

### ISSUE THREAD

**Issue by hosentraeger** [ptvoinfo/zigbee-configurable-firmware#86]
can't select DIO8, DIO9, DIO18, DIO19, DIO25-DIO30 for Status LED in Configurator 1.6.0.0

**Comment by ptvoinfo** [comment]
Hi,

Hmm. What is wrong? Are they missed in the list?

**Comment by hosentraeger** [comment]
correct, not offered in list box

**Comment by ptvoinfo** [comment]
Hmm. I can select it on my computer. Did you select the "CC2652" board type first?

![изображение](https://user-images.githubusercontent.com/33662022/148738592-1534bcd6-3bda-4aac-8e1d-6f43652b027a.png)

**Comment by hosentraeger** [comment]
solved with 1.6.0.1, thank you!
