### ISSUE TITLE
v1.6.0.1  - can't save firmware with professional features

### ISSUE THREAD

**Issue by hosentraeger** [ptvoinfo/zigbee-configurable-firmware#87]
cannot save a firmware that have pro features like PCA9685 or more than four pwm outputs.

Working setup:
Board type: CC2652R1
Device type: Router
Serial bootloader (SBL): P15
Update firmware's timestamp : 2022-01-10
Set default reporting interval (s): 60

Output pins:
P00: Output 1, PWM (Hardware, 128 kHz), External pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level)
P01: Output 2, PWM (Hardware, 128 kHz), External pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level)
P02: Output 3, PWM (Hardware, 128 kHz), External pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level)
P03: Output 4, PWM (Hardware, 128 kHz), External pull-up (Frequency: 1 kHz, Transition time (ms): 0, Linked input: Changes level)
P04: Output 5, GPIO, External pull-up

Broken setup:
after changing P04: Output 5 to PWM, then hitting "Save", the configurator hangs

**Comment by ptvoinfo** [comment]
At this moment, the configurator displays a new dialog window where asks for the license key and device ID.

![изображение](https://user-images.githubusercontent.com/33662022/148880710-1448b882-5c55-426a-b016-3da36e3ed430.png)

**Comment by hosentraeger** [comment]
This seems to be an individual problem with my notebook, where the new dialog won't show up. I just tested successful on another notebook (Windows 10). I'll test again on my personal notebook.

**Comment by ptvoinfo** [comment]
What OS does your personal notebook have?

**Comment by hosentraeger** [comment]
It's Windows 11. I'll check details later.
What I remember, after downloading and starting the EXE for the first time, Windows reports a potential security issue, I have to click "launch anyway" or something. 
Will also de-activate Virus scanner which might interfere with the server communication (its Avira).

**Comment by hosentraeger** [comment]
Here's my system info:
![image](https://user-images.githubusercontent.com/1233312/148988910-b28fe592-3505-4a15-a409-3b0935e22b25.png)

example firmware config:
![image](https://user-images.githubusercontent.com/1233312/148989523-29e0fea0-101d-4d10-a833-4cfd18366fb6.png)

after pressing "Save" nothing happens, program does not respond, can only kill from task manager

**Comment by ptvoinfo** [comment]
It seems that the dialog window appears in the background on another monitor. I cannot repeat this issue on my Windows 11 laptop.

**Comment by hosentraeger** [comment]
You are right. I have three monitors but this dialog box was somewhere else, invisible, I was only able to move it to a real monitor by pressing "Alt-Space", then "move" it up.
Thank you!
