### ISSUE TITLE
[BUG] CC2652P as router - internal temperature suddenly goes to 65.434

### ISSUE THREAD

**Issue by glcos** [ptvoinfo/zigbee-configurable-firmware#90]
After a few hours of normal operation the internal device temperature goes to 65.534. Firmware 14-01-2022

`Attribute report received: present_value=65534.0, status_flags=0, description=C`

Other things such as sensors and inputs continue to work ok.

EDIT: Observed that this may be due to the temperature going below zero, thus being negative. Sensor is outside and today the temperature is -3 deg C

**Comment by FrankX0** [comment]
Your observation is correct:
65.534 = 0xFFFE = -2 (16 bit signed integer)

**Comment by ptvoinfo** [comment]
@glcos, I've fixed this issue in the latest version.

**Comment by glcos** [comment]
@ptvoinfo thanks a lot for the update. I will test it soon.
